### ISSUE TITLE
Sample: Flow volume calculation 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#10]
There was an error in the formula provided.  Please use the following.  
If using Method 1: 
Flow Volume (cfs) = Bottle size (liters) \* 0.03532 (convert to cf)/fill time (seconds)
If using Method 2: 
Flow Volume (cfs) = fl_depth (feet) \* fl_width (feet) \* fl_length (feet)/fill travel time (seconds)

In either case convert to GPM using:
Flow volume (gpm) = Flow volumee (cfs) \* 448.8

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
