### ISSUE TITLE
Referral Agency: remove Discontinued from list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#101]
When attempting to remove an item 'Discontinued' from the domain reference agency, get a Loading... message and it never completes.
Steps to recreate:
1) Settings
2) Editing domains
3) Select Reference Agency from drop down list
4) highlight the item to be deleted 'discontinued' in this case
5) click on the Delete button at the bottom
6) click Yes on the confirmation message
Get the Loading...  message

**Comment by gjmkelly** [comment]
done.  you could not remove the item because it caused a foreign key violation since there was a PST_Investigations records with REF_AGENCY_ID = 3.  I set that value to null and deleted "Discontinued" from the list.  This correct behavior and probably the UI should alert the user that they cannot delete a domain value when that value exists in related records.

**Comment by rssidlowski** [comment]
Update the UI to display a message when someone attempts to delete a domain value that has legacy data.

**Comment by gjmkelly** [comment]
I cannot apply all the foreign keys at this point, so please only test on Complainant or Lab Parameter for a  value that you know is used (like Blue Water Baltimore, Ammonia).  You should see the message: ""One or more records in another related table have data with this value.  It can not be deleted from the domain until that is resolved."

reminder to myself: at the city I need to add the following to the web config so the app can see the real reason for failure:
<configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
</configuration>

**Comment by gjmkelly** [comment]
<configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
</configuration>

**Comment by gjmkelly** [comment]
configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
/configuration>

**Comment by rssidlowski** [comment]
Verified.  Ready to be migrated to COB environment.

**Comment by rssidlowski** [comment]
Verified in COB dev.
