### ISSUE TITLE
Map: display investigation name on identify

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#103]
From COB team, would like to see Investigation name added to list.
Steps to recreate:
1) click on Map
2) click on the Identify
3) select an area - samples within the area are listed below
Update the resulting list to include the investigation name(s) associated with each sample
![samplelistaddinv](https://cloud.githubusercontent.com/assets/5039052/5759010/7f3a856e-9c98-11e4-9a11-c7c251cb834d.GIF)

**Comment by rssidlowski** [comment]
This may be challenging since can have multiple investigations associated with one sample.  Investigate what is possible.

**Comment by gjmkelly** [comment]
also added the lab results here (again try to check one with most results)

**Comment by rssidlowski** [comment]
Verified.  Ready to migrate to COB environments.

**Comment by rssidlowski** [comment]
In the case where we have sample associated to multiple investigations, we should allow the user to select which investigation.  See below where two investigations are listed and when I click on the arrow it goes to the second investigation.
![multinv](https://cloud.githubusercontent.com/assets/5039052/5976616/facee6c2-a85d-11e4-8d53-940133a6393e.GIF)

**Comment by gjmkelly** [comment]
There is no easy way to do that and the only gain would be that the user would never have to select from the investigation name dropdown on the sample details page.  I think that the fact that both investigation names show in the list and you can select from the dropdown is proper functionality.

**Comment by rssidlowski** [comment]
Verified in COB dev.
