### ISSUE TITLE
Sample list: include lab test results

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#105]
From the COB personnel:
"Add lab test results to the Sample List so that you don’t have to scroll through the entire investigation page."
On the Sample List, display the associated Lab results: Lab parameter and result pairs.  Below is from COB.
![labresultsonsample](https://cloud.githubusercontent.com/assets/5039052/5760069/2c89b058-9ca0-11e4-829b-8b23b74cccb4.GIF)
Alternatively, could display as follows:
Sample Label: Northern Pkwy & Fenwick Culvert West Cell
Sample ID: 15836
Sample Data: 2015-01-06 7:03:00 AM
Location Type: Initial
Parameter: 1,1,1-Trichloroethane
Result: =0.005
Parameter: BOD5
Result: =5.25

**Comment by gjmkelly** [comment]
not many samples actually have labs, but please try to find one with the maximum to make sure that displays OK

**Comment by rssidlowski** [comment]
Verified.  Please migrate to COB environments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
