### ISSUE TITLE
Sample descriptors: Change from toggle to selection

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#106]
From COB Personnel: I think this may have been miscommunicated, in the original database it was impossible to select more than one choice for each of these categories, there are multiple fields for each.  There were 3 fields used for each parameter, the first was a yes/no field, the next had a D next to the category name Odor D for description, and the last had the category name followed by a C (Odor C) for comments. The change would result in just 2 fields for each a drop down and a comment:
![colorodordropdown](https://cloud.githubusercontent.com/assets/5039052/5760292/84f2b612-9ca1-11e4-9c9d-1d64e9aceb67.GIF)

For the following values, change in the database and in the application from toggle to selection of only one per category via a drop down box.
Odor: Petroleum, Rancid/Sour, Rusty/Sweet, Sewage, Sulfide, Other
Color: Blue, Brown, Gray, Green, Orange, Red/Rust, White, Yellow, Other
Turbidity: Cloudy, Opaque, Sediment, Slight Cloudiness, Other
Floatable: Petroleum, Sewage, Suds, Other
Pipe Benthic: Gray, Green, Red/Rust, Other

**Comment by gjmkelly** [comment]
I re-added the "toggle" fields so the UI should work (but all are null now).
I added the tables:
PST_LU_ODOR
PST_LU_COLOR
PST_LU_TURBIDITY
PST_LU_FLOATABLE
PST_LU_PIPE_BENTHIC
with values as provided (all just single column lookup tables) and fields in PST samples:
ODOR
COLOR
TURBIDITY
FLOATABLE
PIPE_BENTHIC
(the related comments fields stay as is)
I created foreign keys for each case.
Please let me know if I should proceed with the UI revision and/or bother to migrate the old data to these new fields

**Comment by rssidlowski** [comment]
Please go ahead with the UI change and we will need to get the data there so we will need the data migrated at some point, so please proceed with that.

**Comment by gjmkelly** [comment]
done on form and associated schema and data changes.  I need to change my data migration routine and will assign that task to myself

**Comment by rssidlowski** [comment]
Verified in COB dev.
