### ISSUE TITLE
Sample: unable to clear or unselect drop down items

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#107]
From COB Personnel: unable to clear or unselect any field with drop down box.
![clear](https://cloud.githubusercontent.com/assets/5039052/5760972/1f7332e4-9ca6-11e4-86b5-c765787b4b5b.GIF)
Can you have an option to clear or do we need to add domain values of none selected?

**Comment by gjmkelly** [comment]
added values of "None" and/or "N/A" to the domains

**Comment by rssidlowski** [comment]
Added None to domains but why does color have blank line?  See #106

**Comment by rssidlowski** [comment]
Turbidity is spelled incorrectly on the Investigation sample page: 
![turbid](https://cloud.githubusercontent.com/assets/5039052/5922220/c9686bd2-a617-11e4-8e59-e50ae076309b.GIF)

**Comment by rssidlowski** [comment]
Verified, please migrate to COB environments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
