### ISSUE TITLE
Settings: adjust toggle items

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#108]
From COB personnel: In the settings page, can the Inlet markers and Inlet IDs have separate toggles to switch on and off?  Can you add you add an Inlet ID toggle? The stormwater manhole covers and manhole IDs are separate and it is very convenient to turn IDs off while still able to view covers .
![settingsstormwater](https://cloud.githubusercontent.com/assets/5039052/5761030/9c7fbb72-9ca6-11e4-9991-92f85fb44833.GIF)

**Comment by rssidlowski** [comment]
Also need to review all the layers included in this application and where are the ID's for manhole and inlet?

**Comment by gjmkelly** [comment]
This would be a map service change for the Stormwater service (on City server http://10.1.65.43:6080/arcgis/rest/services) not an app change (the app should pick up whatever is in the service).  So inlets should be included like manholes are now (the manhole feature class is in there twice, once with features unlabeled , then again for the sake of labels.  Inlets now are just a single layer that is labeled.  Joe could probably make this change very quickly, but I'll turn it back to you for now.

**Comment by JMurk** [comment]
I went ahead and made the change anyway. It took no time at all.  Let me know if I should roll back changes.

**Comment by rssidlowski** [comment]
Verified.
