### ISSUE TITLE
Map: Display Stormwater End Structure ID on maps

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#109]
From COB personnel: Can you display Stormwater End Structure ID on maps?
![mapdisplayid](https://cloud.githubusercontent.com/assets/5039052/5761067/e9012648-9ca6-11e4-9516-0ed4baa67db0.GIF)

**Comment by rssidlowski** [comment]
Did you already do this?

**Comment by JMurk** [comment]
No.. Do they want this always on or do they want the ability to turn it on and off?

**Comment by JMurk** [comment]
This should be updated now.

**Comment by rssidlowski** [comment]
Verified in COBdev.
