### ISSUE TITLE
Search Investigation: after return to search investigation screen no results displayed

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#11]
To recreate follow the steps below:
1. select search investigation by name
2. enter 'lasalle'
3. get resulting 
![searchbyname](https://cloud.githubusercontent.com/assets/5039052/4724590/f70f82f4-5951-11e4-8813-aac4feecf38b.GIF)
list:
4. Go to investigation details by clicking on right arrow for any item.
5. Click on the left arrow at top of screen to return to search investigation by name screen.
6. Screen is displayed by the search results are gone.
![searchbynamenoresults](https://cloud.githubusercontent.com/assets/5039052/4724614/389b4866-5952-11e4-8705-9d20a15663e0.GIF)

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
