### ISSUE TITLE
Samples: allow only one Initial and one Source for each investigation

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#110]
From COB personnel: Is there a fail-safe way to not allow more than one initial point and source per investigation. There is only one initial sample.  Old database asked if this is your first sample once you select this all other subsequent records for this investigation were by default samples.  
![sampletype](https://cloud.githubusercontent.com/assets/5039052/5761116/3d0ac424-9ca7-11e4-8c94-e7a99be69d7c.GIF)

**Comment by gjmkelly** [comment]
user trying to change a sample to a source or initial, when that location type exists for the investigation, is prevented and informed how to proceed.  I did not test that this works when selecting location type for new sample (not sure of work flow)  I'll look into that.

**Comment by rssidlowski** [comment]
Unable to add a new sample. Getting that loading after select snap.

**Comment by rssidlowski** [comment]
Verified in COB devhttp://dpwdev.baltimorecity.gov/water/PSTwebapi/index.aspx
I get this message which looks good.
![samplelocationdup](https://cloud.githubusercontent.com/assets/5039052/5959728/7f77837c-a79e-11e4-97c5-015f209c7565.GIF)

**Comment by rssidlowski** [comment]
After save and look at the sample, didn't select a type when I go to the location type field, nothing is displayed by when I click on the dropdown I see that source is checked.
Can we make this a required field?
![locsource](https://cloud.githubusercontent.com/assets/5039052/5959803/1fa02e26-a79f-11e4-9097-2112b77f2285.GIF)

**Comment by rssidlowski** [comment]
Verified in COB Dev.
