### ISSUE TITLE
Map: add map button to sample and investigation pages

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#112]
From COB personnel: Can you put a map button on this page or every page so that you can see where the sample was collected on the map?
![sampleaddmap](https://cloud.githubusercontent.com/assets/5039052/5761854/2eae3172-9cac-11e4-90e5-84a2f15c84fc.GIF)

**Comment by gjmkelly** [comment]
Added "view on map" button on top left of samples detail form.  Behavior should be that when clicked map is displayed centered at the sample and highlighted

**Comment by rssidlowski** [comment]
Verified.  Please migrate to COB environments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
