### ISSUE TITLE
Sample: move Dye fields below on screen

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#113]
From the COB personnel: Can you move this group of fields to below Dissolved Oxygen?
![movedye](https://cloud.githubusercontent.com/assets/5039052/5763026/a2e8e764-9cb4-11e4-96d9-4b6660925605.GIF)

**Comment by gjmkelly** [comment]
done

**Comment by rssidlowski** [comment]
Verified.  Please migrate to COB environments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
