### ISSUE TITLE
Wrap text in text fields?

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#114]
Wrap text or allow cell to grow so that we can see entire comment.
![wrap](https://cloud.githubusercontent.com/assets/5039052/5763169/2911ee98-9cb6-11e4-8048-90f06dd98ec7.GIF)

**Comment by gjmkelly** [comment]
revised these form fields as discussed (should we do that for any others?).  Likely need to finetune and might not know until testing on iPad.

**Comment by rssidlowski** [comment]
The fields with the wrapped text have blocked the bottom line.  See below.  The field should not have half of the text displayed.
![wrapfields](https://cloud.githubusercontent.com/assets/5039052/5892846/f38a0b8c-a49b-11e4-9987-f6ba2fe054cc.GIF)

Other fields to adjust:
On Investigation Details page:
Referral Note
QC Comments
Photo pages (both sample and investigation photos)
Comments
Description
On Investigation Samples page:
Comments
Dye Comment
Color Comment
Floatables Comment
Odor Comment
Pipe Benthic Comment
Turbitity Comment

**Comment by gjmkelly** [comment]
I made the changes for each of the noted fields and set all these text boxes to the default size.  There is a property that I can set for the maximum number of rows to display, but it does not work.  This was a known bug back in 2010 that was supposed to be addressed in the next release, but I guess not.  The half-line display is default behavior that I cannot change.

**Comment by rssidlowski** [comment]
This looks much better.  Migrate to COB enviornments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
