### ISSUE TITLE
Investigation Details: add map

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#115]
Add the ability to go to the map location for an investigation, either allowing the user to select a location (initial, source or sample) or just going to the area.

This is similar to #112.

**Comment by gjmkelly** [comment]
Added "view on map" button on top left of form.  Behavior should be that when clicked map is displayed at extent of investigation samples and all samples of the investigation are highlighted with a blueish halo (so you can still see the location type symbology of the feature)

**Comment by rssidlowski** [comment]
working, please migrated to COB environments.

**Comment by rssidlowski** [comment]
Verified in COB dev.
