### ISSUE TITLE
Remove WQMS Outfalls from PST application

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#119]
From the COB personnel: WQMS Outfall - you should not use this layer, it was created in house can be deleted.
![wqmsoutfall](https://cloud.githubusercontent.com/assets/5039052/5922983/e35d7806-a61d-11e4-8f87-afd35a92cf1e.GIF)

Please assign to Gerry when done removing from the map service as we will have a data conversion item for those samples associated to an outfall.

**Comment by JMurk** [comment]
Features have been removed from the map service.

**Comment by rssidlowski** [comment]
Gerry, need to remove from the Settings page.

**Comment by rssidlowski** [comment]
Verified.
