### ISSUE TITLE
Report: PST Sheets - view printable report is blank

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#123]
When running the PST Sheets report and click on the View printable report, the resulting  page is blank.
![pstsheet1](https://cloud.githubusercontent.com/assets/5039052/5977081/961660a2-a862-11e4-83bd-51e00ef53a83.GIF)

![pstsheet2](https://cloud.githubusercontent.com/assets/5039052/5977088/a3f41584-a862-11e4-9816-9682c0930ecb.GIF)

**Comment by rssidlowski** [comment]
Get data retrieval failed for the subreport.  Also, is there something cut off on the right.  See below.
![reportpst](https://cloud.githubusercontent.com/assets/5039052/5980484/ce750c0c-a87e-11e4-879b-5896576b31c2.GIF)

**Comment by rssidlowski** [comment]
Not seeing GPS values on the PST Sheets either.
![missinggpsandsamples](https://cloud.githubusercontent.com/assets/5039052/6021787/477beb2a-ab86-11e4-8c78-7f190e9fcf97.PNG)
Note: Referral is spelled incorrectly.

**Comment by gjmkelly** [comment]
Should all be fixed.  I don't think you are going to see coordinate values for new investigations (does the app do anything to populate that, do they care?)
Something like http://localhost:60123/rptPSTtrack.aspx?name=135
will show you that it works for the report when the data is there.

**Comment by rssidlowski** [comment]
Verified. I will close for now and see if they complain about the missing gps for new investigations.
