### ISSUE TITLE
Report: view printable report header is wrapping to second line

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#124]
When viewing a printable report the header is going to a second line:
![headerwrap](https://cloud.githubusercontent.com/assets/5039052/5980722/520ea1b6-a881-11e4-9174-74966f119d64.GIF)

Adjust so the Water Quality Management Section appears on the top line.

**Comment by gjmkelly** [comment]
I could never repeat this, but I moved the "Water Quality Management Section" text to the left on each of the reports.  let me know if you still observe the wrapping issue for this or anything else on the reports.

**Comment by rssidlowski** [comment]
Verified in COBDEV: http://dpwdev.baltimorecity.gov/water/activitymanager/index.aspx.
