### ISSUE TITLE
Lab Results: change label to Field Results

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#125]
Latest comments from SME at COB:  
![image](https://cloud.githubusercontent.com/assets/5039052/6022671/85932198-ab8c-11e4-8eef-6c89313c8527.png)
![image](https://cloud.githubusercontent.com/assets/5039052/6022711/d251de20-ab8c-11e4-8018-87ca0de40b17.png)

![image](https://cloud.githubusercontent.com/assets/5039052/6022701/bbf69e04-ab8c-11e4-87ee-f4f66fa227df.png)
![image](https://cloud.githubusercontent.com/assets/5039052/6022707/c84c5afe-ab8c-11e4-8d94-5e98e9eea44e.png)

**Comment by rssidlowski** [comment]
Change the label from lab results to field results.
Actually change to have two results: lab and field since you are displaying both.

**Comment by rssidlowski** [comment]
No longer displaying the field results?  only the lab results?
Should display the ammonia, chlorine from the sample (not lab data).
Actually want to see both field and lab data results.

**Comment by gjmkelly** [comment]
I'd thought this meant just change the word lab to field.  I've never been retrieving "field" values into the sample lists.  If you see ammonia or chlorine ..., that actually does come from a lab sample, not the field.  So if they want the field data also in the lists, please spell out just what to add, thanks

**Comment by gjmkelly** [comment]
and assign it back to me of course :-)

**Comment by rssidlowski** [comment]
Display the following when displaying the results from an identify:
Name: some sample name                                       Investigation: some investigation name
Date: 7/10/2013 12:50:00 PM                       Field Results: Ammonia=3.4, Chlorine>4.5, Enterococci=4

## Sample ID= 5955, Initial Point                         Lab Results: Kjeldahl Nitrogen (Total)=3.4, Nitrate+Nitrite-                                                                        Nitrogen<0.02

The field results are from the sample detail page. The lab results are form the lab data page.
Similarly on the list of samples for an investigation, there is a list of samples with the field results label.  Display  both the field results and the lab results here.

**Comment by rssidlowski** [comment]
Verified.
