### ISSUE TITLE
Lab Name: remove WQMIS - migrate to OCAL

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#126]
From the SME at COB:  remove all WQMIS and replace with OCAL.  This will include changing the legacy data.  
![image](https://cloud.githubusercontent.com/assets/5039052/6022792/6e06b20a-ab8d-11e4-8234-f09b0b6c23a0.png)
![image](https://cloud.githubusercontent.com/assets/5039052/6022800/78e56d4c-ab8d-11e4-9fe6-61523162657c.png)
Fields included are 
Lab Name
Complainant Category
Complainant
Origin

**Comment by gjmkelly** [comment]
done, I'll assign myself a task to remember this for the next migration

**Comment by rssidlowski** [comment]
Verified.
