### ISSUE TITLE
Personnel: missing personnel in data migration

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#127]
From the SME at COB some of the comparison of data appears to have missing personnel.
I spot checked some of the samples and is appears the Van Sturtevant is on the samples from the current system but not in the new PST database.  Please review the data migration for personnel.  
See the following sample id's
16 - Plainfield Ave. & Gardenville Ave. for Investigation: Lasalle
legacy table has: Cherigo, Matsuo, Eucare and Sturtegant
new has: only Cherigo and Eucare
![image](https://cloud.githubusercontent.com/assets/5039052/6023426/c7c38c46-ab92-11e4-9c11-c9aeed5d0e3e.png)

3242 - Plainfield & Gardenville for investigation: Lasalle
legacy table has: Eucare and Sturtevant
new has only Eucare

**Comment by gjmkelly** [comment]
With our changes to handling personnel this has been messed up since just after the initial migration.  I thought that was a known issue and I'll get it right in the next migration.  But, if it's worth me spending a couple hours to fix it now, let me know -- otherwise just let them know the situation.

**Comment by rssidlowski** [comment]
verified.

**Comment by rssidlowski** [comment]
Please make changes as shown in the spreadsheet sent in email.  the main change was Daisuke Matsuo is a former employee not a contractor.
The others in the list with contractor=No should be additional personnel.
The people in the list with contractor=yes should be in the contractor. 
See personneledit_20150428.xlsx.

**Comment by gerrykelly** [comment]
updated in dev as described in email

**Comment by rssidlowski** [comment]
in sample 6872 D. matsuo still appears as contractor personnel and also shows in the personnel.  Should only appear as personnel?

**Comment by gerrykelly** [comment]
Fixed.  I had updated, but did not first delete existing values.  i also had missed some contractors that should have gotten into the samples table -- should be good now.

**Comment by rssidlowski** [comment]
Verified.
