### ISSUE TITLE
QC reviewer - add drop down

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#129]
Add the ability to select a person from the personnel list as a QC Reviewer on the investigation detail page.  
Add a constraint so that the person that entered the investigation is not allowed to be the QC reviewer.
The only investigators who are part in an investigation are familiar with the event and all the sample points, so the QC should be done by someone on the team other than the data enterer.  (Ex. Mike, Matt and Van were the investigators on an event. Van entered the data, so Mike or Matt should check that the data was entered correctly.)

**Comment by gjmkelly** [comment]
ready to test given that we're not going to check data-enterer vs. QC'er.  To avoid a schema change this required code unlike other dropdowns, so please test in a couple ways and keep an eye on it afterwards.

**Comment by rssidlowski** [comment]
Looks fine.
