### ISSUE TITLE
Sample Personnel: need method to test and verify the personnel associated with samples

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#13]
There are no personnel to select from and associate to a sample.  Can we load data so that I can verify compared with existing personnel data associated to the sample records?

**Comment by rssidlowski** [comment]
I don't see the personnel assigned to samples.  For example, sample 1524 Herring Run @ Pump House Run when I click on the personnel button I don't see any personnel.  
![emptypersonnel](https://cloud.githubusercontent.com/assets/5039052/4831888/01037b02-5f98-11e4-9840-91e68f42eedd.GIF)

**Comment by kanglu666** [comment]
because there is no personnel associated the sample.
from drop down "Personnel" field, chose one personnel, then click "Add" button to add the personnel to the sample

**Comment by rssidlowski** [comment]
I have looked at several existing samples and the personnel are NOT appearing in the screens.
For example, from the legacy data
![sampleswpersonnel](https://cloud.githubusercontent.com/assets/5039052/4843479/aa3fe2ba-6032-11e4-919b-7bb309abca4b.GIF)
But when I look in the app for some of these:
![sample6745](https://cloud.githubusercontent.com/assets/5039052/4843491/de449bfa-6032-11e4-8195-7bf7251ad201.GIF)
and when I click on Personnel, I see an empty list...

Please stop over and we can view together.

**Comment by kanglu666** [comment]
In our data model, we have a reference table to associate sample and personnel.
it's empty, i believe we need to migrate the data you list above into that table.

**Comment by rssidlowski** [comment]
Gerry,
Can you populate this table (PST_PersonelXsamples)?

**Comment by gerrykelly** [comment]
not worth the effort now, I will get this right for the final migration

**Comment by rssidlowski** [comment]
Verified.
