### ISSUE TITLE
relative operator dropdowns do not default to '=' 

### ISSUE THREAD

**Issue by gjmkelly** [rssidlowski/Pollution_Source_Tracking#130]
With working on getting the field results in the list i noticed that we are getting nulls for the relative operators.  Lu's code is as good as it can be for setting them to a default '=', but does not work.  I'll fix it, but please verify that is what you see now (the user should not need to explicitly set the value, although I could go that route with a check and a messagebox that prevents saving the record if the their is a value for ammonia, but not a =,>,<)
Assign this back to me, then I'll reassign when ready for test.  Thanks.

**Comment by rssidlowski** [comment]
Working in cob dev: http://dpwdev.baltimorecity.gov/water/pstwebapi/index.aspx.
