### ISSUE TITLE
Investigation: QC Status not displaying

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#135]

**Comment by gjmkelly** [comment]
Please elaborate.  I see the new "QC Status and Date" option on the general search page, then it works fine from the new QC Status and Date search page and QC Status appears correctly on the selected investigation details

**Comment by rssidlowski** [comment]
Sorry, here is a screen shot. After I select the item it does not display in the QC Status box.
![qcstatus](https://cloud.githubusercontent.com/assets/5039052/6379961/0e447ed2-bd04-11e4-9e63-0fa2badfd158.PNG)

**Comment by gjmkelly** [comment]
This is actually a problem intrinsic to ALL select fields in Sencha. It's amazing it never came up before.  Anyway, after figuring out what wasn't working, I put in code to clear the selected value on all the dropdowns whenever the investigation or samples forms are shown.  Let me know if we need this feature elsewhere.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
At one point I noted that we need a way to clear a drop down if someone selects a drop down value by mistake there is no way to clear it.  We added N/A for some drop downs but for others there is no way to clear it.

**Comment by gjmkelly** [comment]
Without a big pain of a workaround, the value of the combobox in Sencha Touch must come from the selected value in the dropdown once a value has been selected once.  So, the right approach is to put the "N/A", "Unknown", "None" or whatever values into the lookup tables that that provide the values for the dropdowns,  If any more tables need such values, that's no problem.

**Comment by rssidlowski** [comment]
I added N/A to QC Status and I think all other dropdowns are fine.
