### ISSUE TITLE
Zoom value after sample selected using identify feature

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#136]
From COB personnel: 
There appears to be a default zoom value that the map goes to after a sample is selected from the identify feature.  In some cases where there are several clusters of separate sample points the map view will zoom out beyond the ability to distinguish the clusters.  Is there a way to leave the zoom value as it was prior to sample selection?
Before sample is selected: 
![beforeidsamp](https://cloud.githubusercontent.com/assets/5039052/6491953/c3c972a6-c27e-11e4-8a49-ccc2a14b2c11.jpg)
After selecting sample.
![afteridsamp](https://cloud.githubusercontent.com/assets/5039052/6491957/cb199cf2-c27e-11e4-83d5-64c68986733b.jpg)

**Comment by gerrykelly** [comment]
The scale it zoomed to was not exactly fixed.  But what I did was to preserve the existing zoom-to behavior when you are zoomed out beyond around what was the zoom-in scale and only center the map on the feature highlighted by the list selection when you are already zoomed in past that level (so never will zoom out a meaningful amount anymore.  If the center-on-the-point is annoying and no action other than highlighting is preferred that's a quick change.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
COB Personnel comment: 
It would be helpful in identifying individual samples within a tight cluster if the search radius could be adjusted smaller than 25’.  Possibly as small as 5’ and with smaller increments of change.

**Comment by gerrykelly** [comment]
Yeah, I don't know why that search slider was set like that.  I made it max 50', min 2-ft default 20' and adjusts in 2' increments

**Comment by rssidlowski** [comment]
Verified.
