### ISSUE TITLE
Change SDUO field from yes/no to drop down; rename to Discharge Classification

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#137]
From COB Personnel (Van Sturtevant):
Can you change the “SDUO” field from a yes/no toggled field to a drop down box? The new field will be named “Discharge Classification,” with the following items in the drop down list: SDUO, SSO, SSO_Private and Potable Water.  Please make the items in the drop down list editable. Also all the current “SDUO” records with a Yes are going to be changed to SDUO in this new “Discharge Classification” field.

The current SDUO in the application shown below should change to have a drop down.
The Discharge classification should also be allowed the user to change the domain values.
The report for SDUO needs to be changed  to allow  user to select one of all values for the discharge classification.
![sduonew](https://cloud.githubusercontent.com/assets/5039052/6803051/74a6969e-d20b-11e4-9c5e-5dfdf2e690d0.PNG)

**Comment by rssidlowski** [comment]
Van mentioned that he added a new field, SDUO_SSO and is updating the existing data in the current app (not the new one being developed), so will need to incorporate this in the final data migration.  The new field has an alias of discharge classification.

**Comment by gerrykelly** [comment]
I did this for BOTH investigations AND samples since that seemed to make sense
We need to clarify what the SDUO report should be since 1) I don't get the headings in the sample vs. our data scheme, 2) We now, I'd think, would like to include the discharge classification in the report records and note which discharge classifications were included on the report header

**Comment by rssidlowski** [comment]
Correct typo: 'Discharge Classifaction' should be 'Discharge Classification'.

**Comment by rssidlowski** [comment]
For report details see #46

**Comment by gerrykelly** [comment]
There was a problem with the latest build where nothing you test was quite current, but close.  The typo was fixed, but more so I think the old SDUO was still on Investigations detail.  That's updated now.  However we might need to revert samples/SDUO to what it had been.  Let's discuss.

**Comment by rssidlowski** [comment]
Awaiting clarification from COB personnel.

**Comment by rssidlowski** [comment]
Where did Van put the discharge classification?  You said at the investigation level, correct?

**Comment by gerrykelly** [comment]
yes, incidents now has the SDUO_SSO field with its new values.  The last field in samples is still SDUO with Yes/No values -- no SDUO_SSO there

**Comment by rssidlowski** [comment]
I received clarification from Matt Cherigo (COB) and they would like the discharge classification at the investigation level with the four levels and the SDUO Sample as Yes/No and default to No.

**Comment by gerrykelly** [comment]
Should be good now as we discussed.

**Comment by rssidlowski** [comment]
Verified.
