### ISSUE TITLE
Export all PST data to an Excel file

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#138]
From COB personnel:
This there a way to export all of the PST data into an Excel file?

**Comment by gerrykelly** [comment]
Sure, that can be done from Excel (2010 for this example) in a number of ways (as a onetime import or as linked tables.
Currently one way is to choose "data" from the menu in Excel > select "from other sources" > select SQL Server, then enter the server info for development (they need to know it will change for Prod.)
so .... 10.1.65.39\dpwdev, GIS_ADMIN & the password is all they need.  Then they can then select the Pollution_Source_tracking database and import tables (they need to know the schema and understand fields have codes and LU tables have values).
If they are not allowed to have the PW for GIS_ADMIN, then could they have a read only account to do this?

**Comment by gerrykelly** [comment]
Thinking about it, if they want this ability there definitely needs to be a user for them created with readonly on GIS_ADMIN's tables in the Pollution_Source_tracking database.  That's an Ian request,

**Comment by rssidlowski** [comment]
Can we have an export to excel option/button from the application?

**Comment by gerrykelly** [comment]
Yes, but this would be some work,  I'll respond by email.

**Comment by gerrykelly** [comment]
I'm assuming this only needs to work when using the app from a Windows computer (download via Chrome)

**Comment by rssidlowski** [comment]
Yes that is correct.

**Comment by gerrykelly** [comment]
working from windows/chrome (might need to enable popups for site).  I still need to tweak some queries.

**Comment by rssidlowski** [comment]
Can you add a confirmation message prior to starting the Excel download to say:
You are initiating export of full PST database to Excel.  You will then be prompted to download.  Continue? 
Add a Cancel and OK button. 
Also what happens if two people do at once?
Update the message: 
![excelwb](https://cloud.githubusercontent.com/assets/5039052/7179622/f59f6b28-e407-11e4-92f3-121a7056192c.PNG)
to:
Excel workbook has been created on server.  Click OK to download.

**Comment by gerrykelly** [comment]
Done.  The buttons on the new message box are the Sencha defaults, I can customize if it really matters.  The probably-needing to allow popups for the site to get the download is annoying.  I could add a message about that.  I could code it differently but that would take some time.  But, if it's in the user guide and they've done the download once, that's probably good enough for what they need. 

I thought about the "two people do at once" issue when I started this and said to heck with it.  If would fail for at least one of them so they'd need to retry.  I just figure this would just about never happen and is not worth the order-of-magnitude more effort to manage concurrent processes and downloads.

**Comment by rssidlowski** [comment]
Verified.
