### ISSUE TITLE
Data: update sys_type_desc for PST_SystemTypeCodes

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#14]
Current values are:
![systypedesc](https://cloud.githubusercontent.com/assets/5039052/4739941/7c339662-5a08-11e4-9ffa-21a40dd6030f.GIF)
Spell out the values for SYS_TYPE_DESC since they will go on the report.
Inlet
Manhole
Outfall
Other
Storm Drain
Sanitary
Stream

**Comment by gerrykelly** [comment]
Done

**Comment by rssidlowski** [comment]
'Stream' is coded as ' Stream'.

**Comment by gerrykelly** [comment]
fixed

**Comment by rssidlowski** [comment]
Verified.
