### ISSUE TITLE
Add CSR layer to PST

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#140]
Add CSR layer, allow user to toggle on and off and by default have turned off.

**Comment by gerrykelly** [comment]
There are actually 3 "*CSR" map services -- water_csr, storm_csr & sewer_csr -- so I added them all:
1) The water_csrs looks like they are already included in the WATER mapservice in the app, but they never seem to become visible, so whatever the case we can ignore the duplication for now
2)  Keep in mind that when you make these CSR services visible, some of their included layers are still not visible and would need to be turned on individually.

**Comment by rssidlowski** [comment]
Verified in COBDev.
