### ISSUE TITLE
Add investigation name to the sample list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#142]
From COB Personnel: 
Add investigation name to the sample list (accessed from investigation page)
a.       Preferably  in the orange field at top 
                        or
b.      below the sample name (second option)
      i.      Sample id # does not need to be displayed  
![samplelist](https://cloud.githubusercontent.com/assets/5039052/6896139/124a40d6-d6b6-11e4-85c2-1ee29db1c53b.gif)

**Comment by gerrykelly** [comment]
investigation name now appears on title bar left of the "new sample" button.  I removed sample ID (but do not approve :-)

**Comment by rssidlowski** [comment]
Verified,
