### ISSUE TITLE
Make personnel a required field

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#143]
From COB personnel:
Is it possible to make personnel a required field?

**Comment by gerrykelly** [comment]
Not 100% foolproof bc I can't reasonably change the workflow where the sample needs to exist before the personnel are added, but this would make it difficult to leave a new sample without personnel or to delete all personnel for an existing sample.

**Comment by rssidlowski** [comment]
Looks good.
