### ISSUE TITLE
Adjust symbology for manhole

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#144]
From COB Personnel: It is difficult to tell if a sample is on a manhole.  Below are some recommendations.  Please do what is possible, we just do not want the sample markers any smaller.
a.       Larger manhole icon?
b.      Add a circle around the diamond if snapped to a manhole?
We were hoping to identify storm drain manholes that have been sampled while leaving the storm drain manhole ID turned off.   Intersections that have many features and samples (31st & Charles, Pulaski & Dean) are much clearer to view without relying on the numbers.   In addition, not all manholes have an ID # (Clinton & Fairmount).  If the manhole icon cannot be larger,  would a square sample marker be possible?   On the Arc Pad screen shot below we can still see the manhole below the sample marker.

![manhole](https://cloud.githubusercontent.com/assets/5039052/6967464/7b97bb8a-d92d-11e4-8d07-d4ce38b231f1.PNG)

**Comment by rssidlowski** [comment]
Symbology was adjusted, but have the Hydrants legend at the top and it is not accurate.  Changed the legend to be not only color coded bu there are different symbols based on status. See current legend:
![legend](https://cloud.githubusercontent.com/assets/5039052/7044784/2d8d9f62-ddc5-11e4-81fa-43f4c5706424.PNG)

Need to update the Hydrants symbology in the Settings.  Currently displays: 
![hydsettings](https://cloud.githubusercontent.com/assets/5039052/7044825/9506130e-ddc5-11e4-89eb-a9b984245b14.PNG)

Symbology developed:
green hydrant with star - In service
gray hydrant with black circle - Null
yellow hydrant with plus sign -  In service repairs needed
red hydrant with square - Out of service

**Comment by gerrykelly** [comment]
Joe, can you add a symbolized-for-PST wa_manhole as the last layer \dpw-gis102dev-srv\MXD\Maps\PST_Samples.mxd and republish for the PST_samples map service?

**Comment by JMurk** [comment]
PST_samples is a feature service, therefore I cannot add anything to it from a different data source.  I can create a separate Stormwater service for PST with larger Manhole features?

**Comment by gerrykelly** [comment]
Yeah, I thought of that a little too late.  A new service, like STORMWATER_PST, might be the only way.

**Comment by JMurk** [comment]
I published a service called Stormwater_PST on dev with larger manhole symbols.

**Comment by rssidlowski** [comment]
Looks good.
