### ISSUE TITLE
Settings: PST all points

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#147]
What is the purpose of the 'All Points' button on the settings, pollution source tracking?  I don't see that anywhere on the map.
![settingspst](https://cloud.githubusercontent.com/assets/5039052/7055669/4d15c00a-de13-11e4-8053-77e713766693.PNG)

**Comment by gerrykelly** [comment]
That button is automatically generated as a result of the samples featureclass (with no definition query) being included in the map service for the sake of queries/spatial operations.  It serves no purpose for display.  It would be a pain to write code to keep the ESRI legend component from showing the layer as in the image above.  If it's worth the effort, let me know.

**Comment by rssidlowski** [comment]
No worries.   Just curious.
