### ISSUE TITLE
Report: PST Report

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#15]
Create a report with the following specifications:
PST Report
Input:
• Date Range (or all dates)
• Investigation name (or all investigations)
• Watersheds (or all)
Fields:
• Name – PST_Investigations.INV_NAME
• PST Resolved – PST_SAMPLES.RESOLVED
• Location – PST_Investigations.LOC_DESC
• Video Inspection – PST_SAMPLES.VIDEO_NEEDED
• Problem Type – PST_ProblemCodes.PROBLEM_DESC
• Initial GPS North – PST_SAMPLES.LAT WHERE pst_location_type_lu.location _type_id=1 (initial)
• Initial GPS West – PST_SAMPLES.LONGI WHERE pst_location_type_lu.location _type_id=1 (initial)
• Source GPS North – PST_SAMPLES.LAT WHERE pst_location_type_lu.location _type_id=3
• Source GPS West – PST_SAMPLES.LONGI WHERE pst_location_type_lu.location _type_id=3
• Field Date - PST_Investigations.INV_FIELDDATE  
• Referral Date - PST_Investigations.REF_DATE  
• Follow up Required – PST_SAMPLES.FOLLOW_UP
• Origin – PST_OriginCodes.ORIGIN_DESC  
• Complaint Date – PST_Investigations.INV_COMPLDATE
• Referral – PST_RefAgencyCodes.REF_AGENCY_DESC
• Complainant – PST_ComplainantSourceCodes.COMPLAINANT_SOURSE_DESC  
• Date Solved  – PST_Investigations.INV_SOLVEDATE
• SR Number – PST_SERVICE_REQUEST.SR_NUM
• Status – PST_InvStatusCodes.INV_STATUS_DESC
• Repair Date - PST_Investigations.INV_COMPLETEDATE  
Below for each Sample line:  
• GPS North - PST_SAMPLES.LAT WHERE pst_location_type_lu.location _type_id=2 (for each sample)  
• GPS West – PST_SAMPLES.LONGI WHERE pst_location_type_lu.location _type_id=2 (for each sample)  
• Date - PST_SAMPLES.SAMPLE_DATE
• Time - PST_SAMPLES.SAMPLE_TIME
• System Type – PST_SystemTypeCodes.SYS_TYPE_DESC  
• Flow Rate – PST_FlowRaveCodes.FLOW_RATE_DESC  
• Location – PST_SAMPLES.SAMPLE_LABEL  
• Dye Test – PST_DyeTestCodes.PST_DYE_TEST_DESC, PST_DyeColorCodes.DYE_COLOE_DESC  
• Personnel – PST_Personnel, PST_PersonelXsamples for this sample  
• Sample Type - pst_location_type_lu.location _type_id for each sample line
![rep1_psttracking](https://cloud.githubusercontent.com/assets/5039052/4741888/aaded29e-5a1a-11e4-8f59-bc6f717c7b64.GIF)

**Comment by rssidlowski** [comment]
Per Brendan, use SQLServer reporting services.

**Comment by rssidlowski** [comment]
Get the following error when viewing the PST report: data retrieval failed for the subreport.
![reportpstsubreporterror](https://cloud.githubusercontent.com/assets/5039052/5106429/1837bf2a-6fc6-11e4-9782-5fcce52038b2.GIF)

**Comment by rssidlowski** [comment]
PST sheet report is empty in printable report tab.
I generate the report: 
![pstrpt1](https://cloud.githubusercontent.com/assets/5039052/5493736/909a7316-86bb-11e4-89c0-cabed5d5ff23.GIF)
but when I click on view printable report the new tab opens and it has no data.
![pstrpt2](https://cloud.githubusercontent.com/assets/5039052/5493755/ab909470-86bb-11e4-9072-d5ee55c2a1fb.GIF)

**Comment by gjmkelly** [comment]
This does not appear to be an issue on the reports side.  i.e. if you use the URL -- http://vm-1108s08/Allreport/rptPSTtrack.aspx?date1=10/10/2012&date2=12/12/2012 -- and export to PDF it's fine.  So I think it is in the activity manager that I know nothing about.  I'll send it back to you for now (maybe Lu or Jesse can fix this quickly, or assign it back to me and I'll have to learn this part)
