### ISSUE TITLE
Sample system types in code do not match lookup table and should be reviewed for intent

### ISSUE THREAD

**Issue by gerrykelly** [rssidlowski/Pollution_Source_Tracking#150]
need to discuss and fix

**Comment by gerrykelly** [comment]
Here are the values of interest -- for when a sample is created/moved with the snap-to option -- from PST_SystemTypeCodes vs. what Lu had in code (keeping in mind that we don't even want to use "Storm Drain" bc that's a line feature class).  As you can see, the values 8 & 9 in code are not even valid.  So, please clarify which layers that show up in the eligible snap-to features list match what values in the lookup table and I'll edit the procedures as necessary.  

1   IN          Inlet
2   MH          Manhole
3   OF          Outfall
4   OT          Other
5   SD          Storm Drain
6   SN          Sanitary
7   ST          Stream

if (this.currentSourcefeature.data.layerName == 'Stormwater Manhole') { dataobj.SYS_TYPE_ID = 2; }
                if (this.currentSourcefeature.data.layerName == 'Wastewater Manholes') { dataobj.SYS_TYPE_ID = 9; }
                if (this.currentSourcefeature.data.layerName == 'Stormwater Inlets') { dataobj.SYS_TYPE_ID = 1; }
                if (this.currentSourcefeature.data.layerName == 'Stormwater Drains') { dataobj.SYS_TYPE_ID = 5; }
                //if (this.currentSourcefeature.data.layerName == 'WQMS Outfall') { dataobj.SYS_TYPE_ID = 3; }
                if (this.currentSourcefeature.data.layerName == 'Stormwater End Structure') { dataobj.SYS_TYPE_ID = 8; }

**Comment by rssidlowski** [comment]
The system should allow the user to snap and see all the features
We have current samples of all these types:
Inlet (276)
Manhole (3573)
Outfall (883)
Sanitary (1124)
Storm Drain (333)
Stream (649)
Other/None (467)
The system does not allow to associated a new sample with the following:
outfall
sanitary
storm drain
stream

To answer your question above, I thought they didn't want to include outfall (but we need to include the type to support the legacy data).  So, I would adjust above as such:
if (this.currentSourcefeature.data.layerName == 'Stormwater Manhole') { dataobj.SYS_TYPE_ID = 2; }
 if (this.currentSourcefeature.data.layerName == 'Wastewater Manholes') { dataobj.SYS_TYPE_ID = 2; }
 if (this.currentSourcefeature.data.layerName == 'Stormwater Inlets') { dataobj.SYS_TYPE_ID = 1; }
 if (this.currentSourcefeature.data.layerName == 'Stormwater Drains') { dataobj.SYS_TYPE_ID = 5; }
 //if (this.currentSourcefeature.data.layerName == 'WQMS Outfall') { dataobj.SYS_TYPE_ID = 3; }
 if (this.currentSourcefeature.data.layerName == 'Stormwater End Structure') { dataobj.SYS_TYPE_ID = 3; }

Let me know if we need to discuss.

**Comment by gerrykelly** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
