### ISSUE TITLE
Migrate PST database to COB Production

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#151]
Migrate the PST database and map services to the COB production environment.  
The application is going to be staged in the COB production environment and Gerry will do another test migration prior to the final migration starting 5/1/2015 to be ready for go live on 5/4/2015.

**Comment by gerrykelly** [comment]
I think I finally managed to create a SQL Server 2008R2 version of the Pollution_Source_Tracking DB on vm-1108S08dev.  Please see if you can backup then restore in City production and create the map ervices  There were a lot of problems and corrupted objects during my first many attempts and I don't have a good way to really test until everything gets in production, so please let me know if you have any issues along the way.

**Comment by JMurk** [comment]
What is the correct db on 1108s08?

**Comment by JMurk** [comment]
Database and all associated map services have been published in production.
