### ISSUE TITLE
Unable to delete photos

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#152]
Once photos are added (either to investigation or sample), unable to delete them. Should be able to select a photo that was updated and be able to view, update or delete.  I don't see the options at all for either investigation or sample photos.
![photodelete](https://cloud.githubusercontent.com/assets/5039052/7188229/3dfd50f6-e444-11e4-87d9-f76228c5dcf6.PNG)

**Comment by gerrykelly** [comment]
Similar problem found for investigation photos and sample photos (but they are separate forms and different code.  Should be fixed in both cases.

**Comment by rssidlowski** [comment]
Verified.
