### ISSUE TITLE
Data conversion: flow volume

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#154]
Looks like the data conversion needs to be corrected for flow volume calculations.
From the legacy system see this sample for 801 N. Linwood: 
![flow1](https://cloud.githubusercontent.com/assets/5039052/7282327/50d047ca-e8fd-11e4-8c97-f7603f7830f2.PNG)
 See flow tab and note flow volume is 3 liter bottle, time is 60 sec: 
![flow2](https://cloud.githubusercontent.com/assets/5039052/7282339/655b14c2-e8fd-11e4-9db7-91260ddaa9f0.PNG)
Here is the legacy data table:
![flowsamplelegacy](https://cloud.githubusercontent.com/assets/5039052/7282359/8a3ffadc-e8fd-11e4-9d3a-c925f96f9842.PNG)
But after the conversion the pst sample table has
![flowsamplenew](https://cloud.githubusercontent.com/assets/5039052/7282372/a0498ab4-e8fd-11e4-84e8-0983cea9cb74.PNG)
The conversion is converting the type (flownum)to the fl_bottle_size and the bottle size (fvolume) to fl_volume_cfs.
See the same sample record in the new PST app:
![flowsampleappnew](https://cloud.githubusercontent.com/assets/5039052/7282490/4aedb3aa-e8fe-11e4-8c9a-b2f546665e51.PNG)

It should be the other way around, convert the flownum to the correct lookup value for flow method.
fvolume should convert to the fl_bottle_size.

Also, the calculations are not being stored in the new solution.
See #10 for the calculations for cfs and gpm.

.

**Comment by gerrykelly** [comment]
I also calced the gpm/cfs for all and increased the number of digits for those fields in the app calc function (since the cfs especially often rounded down to zero)

**Comment by rssidlowski** [comment]
Verified.
