### ISSUE TITLE
Reports: add two new reports to COB activity manager portal for Discharge Classification/SDUO

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#155]
Add two new reports to the Activity Manager portal for PST:
Investigations with Discharge Classifications
- allow user to enter date range
  - allow user to select one to many from domain values: SDUO, SSO, SSO Private, Potable Water
    Investigations with SDUO Samples
- allow user to enter date range

See #46 for report details being developed.

Remove existing placeholder for SDUO report, called Sanitary Discharge Unknown Origin.

**Comment by jday3** [comment]
@gjmkelly, have these reports been created?

**Comment by rssidlowski** [comment]
No.

**Comment by rssidlowski** [comment]
There is a similar that exists that could match one of them.

**Comment by jday3** [comment]
Done, on dev

**Comment by rssidlowski** [comment]
Verified on Dev.  A couple minor items that Gerry needs to fix on reports themselves.

**Comment by rssidlowski** [comment]
These are ready to be migrated to production when you get a chance.

**Comment by gerrykelly** [comment]
the reports exist in production -- just the different URL, but same Activity manager code as you did for dev (if you have not already done that part too)

**Comment by rssidlowski** [comment]
Verified.
