### ISSUE TITLE
Add investigation: Date picker default

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#156]
In COB Production, when adding a new investigation, date picker for complaint date defaults to Jan 1, 2003.  Can this be map to default to the current date?
The same applies to other date fields: field investigation date, date solved, repair confirmed date,  referral date, QC Review Date.

**Comment by rssidlowski** [comment]
![datepicker](https://cloud.githubusercontent.com/assets/5039052/7445640/95b6273a-f189-11e4-9ac5-763cf775d128.PNG)

**Comment by gerrykelly** [comment]
I check this once in a while and have yet to see this.  Does it happen on other computers, for other users, on the iPad?

**Comment by rssidlowski** [comment]
I'm not seeing this in COBDEV.  Was this fixed with #172?

**Comment by rssidlowski** [comment]
Today and clear buttons work great. Verified in prod.
