### ISSUE TITLE
Adding photos: unable to submit

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#157]
This seems intermittent, but when I try to add photos, the bottom area seems to move around.  Not sure how to explain this, but I am unable to get the submit button to do anything.  Please take a look.  I went out and back in and it worked, but trying again and not working.  The appears the same whether uploading to investigation or sample.  I see similar behavior.
![submitphoto](https://cloud.githubusercontent.com/assets/5039052/7445663/91ddbb54-f18a-11e4-8bff-d431fa2da546.PNG)

**Comment by gerrykelly** [comment]
I've never liked the design of the photo upload area and I know what you mean.  There's something wrong with the list layout and I can repeat your issue for samples, but never for investigations (submit always works there).  I'll try to make the samples photo form like investigations and hope that's good enough.  Then that will require a full rebuild and replace of the Sencha code.

**Comment by gerrykelly** [comment]
I think the acute problem is fixed

**Comment by rssidlowski** [comment]
Verified.
