### ISSUE TITLE
Search investigation by status and date not finding investigation

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#158]
I created a new investigation today, 5/3/15 and when I search for investigation with status=on-going investigation and put one date in the from and to, it doesn't find it.
See below for the successful search when I put the range 5/2 to 5/3.
![searchfails](https://cloud.githubusercontent.com/assets/5039052/7445714/631bdb96-f18c-11e4-9798-bcf14ee97856.PNG).

See below for search for today.
![searchfails2](https://cloud.githubusercontent.com/assets/5039052/7445722/c1ec2b30-f18c-11e4-8cdf-86fee27b53e0.PNG)

**Comment by gerrykelly** [comment]
if you set your dates to 5/2 - 5/4 you do get it, so probably in the webservice it does not return anything equal to the start date/end date, just greater than and less than.  I'll take a look

**Comment by gerrykelly** [comment]
Fixed.  I change queries to include the date limits every place I found date range used, but can't be sure I found them all.

**Comment by rssidlowski** [comment]
Verified.
