### ISSUE TITLE
Search by sample name not finding all results

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#160]
When I search for a word in the sample name it is not finding the results.
![searchfails3](https://cloud.githubusercontent.com/assets/5039052/7446138/ad21d474-f19c-11e4-9934-da6a54011c84.PNG)
But when search for sample by beginning, works:
![searchfails4](https://cloud.githubusercontent.com/assets/5039052/7446144/d260af26-f19c-11e4-8951-5f60ef3860d3.PNG)

**Comment by gerrykelly** [comment]
I revised the query in prod to have a leading wildcard so it will now find words in the middle of a sample name

**Comment by rssidlowski** [comment]
Verified.
