### ISSUE TITLE
Dye Test carrying over to other samples

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#162]
COB personnel reported this problem in production.  When reviewing legacy data with samples that have dye test set and go to another sample the dye test values carries over on the display.

To recreate, open an existing investigation, search for Crispy.
![crispy1](https://cloud.githubusercontent.com/assets/5039052/7538847/04fcf9b2-f571-11e4-9d16-1f65dd44e97a.PNG)

Go to samples and look at initial and view dye test.  Note it is blank.

![crispy2](https://cloud.githubusercontent.com/assets/5039052/7538923/97dfa716-f571-11e4-860f-8de1baf8bcac.PNG)
Go to another sample: 230 N. Franklintown Rd. Midway on Driveway 080913 (2) and see dye test=present.

![crispy3](https://cloud.githubusercontent.com/assets/5039052/7538928/a3ec67ec-f571-11e4-9997-a4f716ba39b1.PNG)

Go back to original sample and see dye test=present.  In fact go to any other sample and they all display present.
![crispy4](https://cloud.githubusercontent.com/assets/5039052/7538961/c59f8b12-f571-11e4-9286-446085bac0cf.PNG)

**Comment by gerrykelly** [comment]
I think I got it.  Amazingly it looks like this was only happening for the dye test field and only when there were a lot of samples for an investigation.  So no wonder we did not see it in testing and it's lucky they caught it early.

**Comment by rssidlowski** [comment]
Verified.
