### ISSUE TITLE
Status field as editable domain

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#164]
Can the status field be an editable domain?  What are the implications on the reports that have status in the column?  Are the status values hard coded in any of the reports?

**Comment by gerrykelly** [comment]
Status is dynamic in the reports, so it would be fine for make it an editable domain in the app.  The only question would be if in the activity manager, are the values hard coded to let the user select status (I doubt it, they probably just pull from the table)

**Comment by rssidlowski** [comment]
I checked with Jesse and he believes they are pulling from the table.  Can you make this change in dev and I can test it out?

**Comment by rssidlowski** [comment]
Verified in COBDev.

**Comment by gerrykelly** [comment]
Can this wait to go to prod until the new sample ID functions are tested and ready, or do they want it ASAP?

**Comment by rssidlowski** [comment]
Verified.
