### ISSUE TITLE
Adding new sample using snap then spot incorrectly locating spot sample

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#167]
Reported by Matt at COB. Verified in prod and dev.
To recreate:
1. add new sample using snap method and select a feature, eg manhole, save
2. add new sample using spot method
Error: places the sample on the same spot on the map as the previous sample and not where the spot was.  
Let me know if you need screen shots.

Matt reported that if they add a new sample using the spot method first that is saved at the correct location.

**Comment by gerrykelly** [comment]
cannot replicate

**Comment by rssidlowski** [comment]
I was able to replicate by doing the following in COB Prod:
1) to an existing investigation, create new snap sample (see Regina's test investigation), sample 21957 another test sample is on a manhole
2) create another sample new spot sample (21958) as a spot (note the system type is none), but it placed it on top of the other one at the manhole not where I spotted it.
3) all subsequent additional spot samples are placed correctly, so I cannot reproduce again.

**Comment by gerrykelly** [comment]
I've tried this more than 10 times and cannot get it to happen.  Let's try to repeat at your computer tomorrow.

**Comment by rssidlowski** [comment]
Unable to recreate consistently.

**Comment by rssidlowski** [comment]
From COB personnel: The pattern for this is that when doing a spot right after a snap it fails (as in in moves the new sample to the previous snapped location).  Subsequent samples created with spot work correctly until they create another snap sample and then spot sample.
I was able to recreate once in COBDEV but not consistently.

Also it appears to move it to the snapped location after you hit save after adding personnel.

**Comment by rssidlowski** [comment]
Actually, I added these new spots down in the middle of a house and they were moved to the location of the previous snap.
![newspot_misplaced](https://cloud.githubusercontent.com/assets/5039052/8109774/a36fd3f6-1026-11e5-8fdb-e4654001aff7.PNG)

**Comment by gerrykelly** [comment]
I think I got it.  I was never seeing the problem bc I checked after the initial save for the spot sample and it was always right.  But what was happening is that the app saved the new spot sample at the map-click point like it should, but held onto the location for the last selected feature and applied that when saving an existing sample (so the new spot sample was now existing on the 2nd save and got the old snap location.)  
They might want to recheck spot samples they have added, but I don't think this bug messed up anything else.
Please test a few select>samples, create snap-spot etc and make sure things end up where they should and stay put (I'm confident the original problems is fixed, just looking for anything our of whack before we put this in prod)

**Comment by rssidlowski** [comment]
Looks good from my testing!

**Comment by gerrykelly** [comment]
updated in prod (annoyingly it failed the 1st time I tried, but after a cache-clear it works)

**Comment by rssidlowski** [comment]
Verified in Prod by me and COB personnel:  
Thur 6/18: This morning I verified that the snap/spot and the character limitation issues have been resolved on both the desktop and Ipad. from Matt Cherigo
