### ISSUE TITLE
Personnel: keep in order received

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#168]
From Matt at COB, as personnel are added keep in the order entered.  They are getting sorted to alphabetic by last name. The business reason is they want to be able to see the first person entered (as that is the person that entered the sample into the system).

**Comment by rssidlowski** [comment]
If doing a re-migration of personnel data how would it affect the new data entered since go live on 5/4?

**Comment by gerrykelly** [comment]
We would only remigrate the personnel data itself and would not lose any personnel data they have entered since.  But that "new" personnel data would still not be ordered by assignment sequence.  If they care and know the order they could go back and delete/re-add personnel for each sample.

**Comment by rssidlowski** [comment]
What is the change we are proposing?   Will the personnel order be retained for 'legacy' data if there is a remigration?  Are you planning to add a sequence to the personnel associated to a sample?  I want to understand before I ask the users whether they want to proceed.

**Comment by gerrykelly** [comment]
Ready in Prod too (they do seem to had deleted 3 of the migrated samples their)

**Comment by rssidlowski** [comment]
Verified.
