### ISSUE TITLE
Investigation explanation: make field larger

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#169]
From Matt at COB.
When entering explanation on the investigation, get error shown below.  What is the limit for the field and can it be made larger?  Can we add a countdown for how many characters are left?
![formfielderror](https://cloud.githubusercontent.com/assets/5039052/7705229/031720f2-fe11-11e4-9e03-3bf6d1706ef8.PNG)

**Comment by gerrykelly** [comment]
I made this and a few other investigation fields tp 2000 char and changed the web service to match.  There may be some fields in samples where they will have the same issue, but I did not do anything there since it's a feature class and we'd need to be a little more careful.

**Comment by rssidlowski** [comment]
Verified in cobdev.

**Comment by rssidlowski** [comment]
Verified in prod.

**Comment by rssidlowski** [comment]
From COB, they really need more space for comments on the sample Comments field.  They suggested the same as you have provided for investigation description.

**Comment by gerrykelly** [comment]
sample Comments and several other samples text fields are way upsized in dev & prod.  They don't use the webservices part, so that should be it.

**Comment by rssidlowski** [comment]
Verified.
