### ISSUE TITLE
Snap to sanitary manhole to display sanitary in system type

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#171]
From Matt at COB
When a sample is snapped to a sanitary manhole can the system type in sample page automatically display “sanitary” instead of manhole.  (manhole would be just for storm drain manhole)

**Comment by gerrykelly** [comment]
I'll change 'Wastewater Manholes' to sanitary and leave stormwater Manholes as manhole

**Comment by rssidlowski** [comment]
I added in cobdev to wasterwater manhole and the system type is manhole.  See sample id = 19435.

**Comment by gerrykelly** [comment]
I think this works right (at least for me :-),  I went to your location for sample 19435 and -- although that sample is "manhole" -- when I turned on the Waste Water layer and created a new sample by the snap method at that exact same location, I got "sanitary ".  I've tested by adding new samples to existing investigations and my creating a new investigation and cannot reproduce the error.  Please retry and if you can get it to say "manhole" when it should be "sanitary" try to record the work flow/steps that I replicate.

**Comment by rssidlowski** [comment]
Verified this is working correctly now in COBDEV.

**Comment by rssidlowski** [comment]
Verified in prod.
