### ISSUE TITLE
Settings: unable to toggle layers 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#174]
From COB personnel:
Since Wednesday afternoon we have started experiencing  malfunctions in the app while accessing from the desk top computers.  
1.       We are no longer able to toggle layers on/off in the settings page
2.       Investigation details and sample details pages are now initially blank, then appear after scrolling down but will not allow us to view the lower portions of the pages. 
These problems began affecting some of us on Wednesday and then most of us by Thursday.  We were hoping that it was just a temporary result of the current program revision.   The tablet operation does not have any of these problems.

I tested and can toggle but the application is very slow.  Does something need to be restarted?

**Comment by gerrykelly** [comment]
Hate to say it, but until if & when we figure this out -- try Firefox

**Comment by gerrykelly** [comment]
Fixed in dev and prod

**Comment by rssidlowski** [comment]
Verified.
