### ISSUE TITLE
map service layers do not display features when toggled off then on

### ISSUE THREAD

**Issue by gerrykelly** [rssidlowski/Pollution_Source_Tracking#175]
When you select a visible map service and toggle one or more of its layers off, the layer(s) are no longer displayed.  But when you toggle the layer(s) back on they do not re-display (they will re-display after turning the parent service off and on).

**Comment by gerrykelly** [comment]
Fixed in dev, but let's make sure the fix did not introduce any other problem with the toggling of visibility.

**Comment by rssidlowski** [comment]
When I started testing, I go to Wastewater (or any other layer) and see no values within to toggle on/off.
![settingsmissinglayers](https://cloud.githubusercontent.com/assets/5039052/7865589/e0f02540-0537-11e5-9c63-80aeba26a8a1.PNG)

**Comment by gerrykelly** [comment]
I'm in the same URL -- http://dpwdev.baltimorecity.gov/water/PSTwebapi/index.aspx --
and see the layers. Please clear all history, refresh and try again.
