### ISSUE TITLE
Add all drop downs to editable domain list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#176]
From COB personnel: Add all drop down boxes to Edit Pollution Source Tracking Domains list.
from my review of the application, this includes:
on Investigation:
problem type
watershed
stream name
priority

on Sample:
status
location type
system type
flow rate
dye test
dye color 
color
floatables
odor
pipe benthic
turbidity

On SR:
Reference type

on Photo upload:
Category

flow method (but controls the calculation)

**Comment by gerrykelly** [comment]
The one quirk in this is stream names.  Streams had a foreign key to watershed.  The form filters the streams according to the selected watershed.  So, now if you add a stream via the app it gets a watershed of "None" and these unassigned streams will show up for any selected watershed (someone could later put in the correct watershed ID in the streams table)
For "Reference type" I think you meant "Request Type"
The only domain-like table now missing is PST_VolCalMethodCodes.

**Comment by rssidlowski** [comment]
Verified in COBDEV.  Ready to promote to production.

**Comment by rssidlowski** [comment]
Verified in prod.
