### ISSUE TITLE
pollution source problems layer initial points and samples symbols swapped

### ISSUE THREAD

**Issue by gerrykelly** [rssidlowski/Pollution_Source_Tracking#178]
Looking in dev, it appears that in pollution source problems initial points are the red diamond and samples are the blue circle.  This is the reverse of the symbology from the pollution source tracking layer.  I only checked for specifically for the problem-type-ammonia sublayer, but I'd think it is the same issue for all.  So, please check and if so, resymbolize all and republish for dev and prod.

**Comment by JMurk** [comment]
My fault, sorry for that oversight (and good catch).  I've republished services in both dev and prod.

**Comment by rssidlowski** [comment]
Verified.
