### ISSUE TITLE
Reports: Discharge Classification error

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#179]
Get this error below on Investigations with Discharge Classification
An error has occurred during report processing.
Cannot create a connection to data source 'DataSet1'.
Exception has been thrown by the target of an invocation.
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression. The statement has been terminated.

I was able to recreate in dev: http://dpwdev.baltimorecity.gov/water/activitymanager/index.aspx

**Comment by gerrykelly** [comment]
should be back to working in dev & prod

**Comment by rssidlowski** [comment]
Verified.
