### ISSUE TITLE
Sample list: sort in descending date order

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#180]
From Matt at COB:  Could the sample list be sorted by date with the newest on top instead of newest on the bottom?
On the Sample list page, adjust the sort order so the most recent is at the top.
![samplesort](https://cloud.githubusercontent.com/assets/5039052/8570725/62e1150e-2550-11e5-87b8-2a9272328468.PNG)

**Comment by gerrykelly** [comment]
ready in test

**Comment by rssidlowski** [comment]
Verified in COBDEV.  Please promote to COBProd.

**Comment by rssidlowski** [comment]
Verified in COBProd.
