### ISSUE TITLE
Link Sample: unable to successfully link sample

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#181]
As reported from the PST team: We have found that the Link Sample feature in the PST application does not work correctly.  Several staff members have tried over the past few weeks and all have had the same experience.  After clicking on the “Link Sample” button the application guides us to choose an existing sample to link to the open investigation.  At this time we can choose a sample from the map and it will ask to confirm the link.  After confirming the link by clinking the yes, nothing happens.  The selected sample remains only in its original investigation.

I recreated this behavior in development.  I am unable to successfully link a sample even though the message displays that it was linked.  I don't see the sample in the sample list for the current investigation.

**Comment by gerrykelly** [comment]
I'd never used this feature nor worked with the code for this function, but trying it today (in dev and prod) it has worked as expected every time.  I can't get it to fail.  Can you provide detailed work steps and an investigation/sample that I can use to replicate the error?

**Comment by gerrykelly** [comment]
I think I was able to get the error in dev on my last try, so hold off and I'll try to figure it out

**Comment by gerrykelly** [comment]
This was yet another buried case of a function using objectID instead of sampID!  So, it "worked" when an objectID equal to the sample's sampleID existed in the table.  Should all be fixed now.

**Comment by rssidlowski** [comment]
Verified in COBDev.  Please promote to COBProd.

**Comment by rssidlowski** [comment]
Verified in COBProd.
