### ISSUE TITLE
New fields for SDUO on Investigation Details

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#182]
Requested from PST SME:
OCAL recently hired an engineering to management the SDUO program. He had reviewed the PST App and has made a few quests, which will help him manage the SDUO program. 
1.  Add 15 character text field named “Outfall ID” after or below the “Discharge Classification” field
2.  Add 15 character text field named “SDUO ID” after or below the “Stream Name” field

![newfields](https://cloud.githubusercontent.com/assets/5039052/9173596/34af1eb6-3f49-11e5-80cc-e7de498ff838.jpg)

What will it take to add these to the database and to the user interface?

**Comment by gerrykelly** [comment]
ready in test

**Comment by rssidlowski** [comment]
Verified in COBDev.  Promote to COBProd.

**Comment by rssidlowski** [comment]
Verified in COBProd.
