### ISSUE TITLE
Reports not functional - no data in drop down selection

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#183]
Several reports are not providing any values in the drop down box.  
For example: 
Complaints has drop down for status code and watersheds and when click on the arrow, no values in drop down box. Same for select of watersheds.
The following reports are all unusable for same reason:
Investigations by status for date range
Investigations by Complainant for Date Range
Investigations per watershed by month
Investigations per watershed by year
PST Sheets

**Comment by gerrykelly** [comment]
should work now

**Comment by rssidlowski** [comment]
Verified.
