### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#184]
The Download to EXCEL feature is not working.  It gets as far as Loading and the App remains greyed out until you refresh the screen.  The download never finishes or never actually happens.
![exportloading](https://cloud.githubusercontent.com/assets/5039052/9254712/f9365a72-41b2-11e5-9660-e9392f6cfd3b.PNG)

**Comment by gerrykelly** [comment]
After a lot of debugging, nothing was wrong.  I restarted the webserver and it works again.

**Comment by rssidlowski** [comment]
Verified.
