### ISSUE TITLE
Report: new PST Detail Report

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#186]
New report requested.
![pstdetail](https://cloud.githubusercontent.com/assets/5039052/9408054/1ab02b3a-47dd-11e5-81b8-60734e7e1588.PNG)
COB SME would like this by Monday if possible.  
Please pass to Jesse when done to include on the Activity Manager.

**Comment by gerrykelly** [comment]
I completed the report in DEVELOPMENT based on the image above.  So, the dynamic parameters are start/end dates and the SDUO discharge classifications to be included.  In the activity manager it should be similar to what you have done before for the SDUO reports.  A sample URL is below,  When done please assign to Regina for testing.

http://dpwdev.baltimorecity.gov/SDUO/rptPST.aspx?reportType=detail&date1=03/01/2014&date2=8/22/2015&SDUOS=1,2,3,4,0

**Comment by rssidlowski** [comment]
Extra - under Discharge Classification - displays Classifi-cation.
![newpstdetail](https://cloud.githubusercontent.com/assets/5039052/9474416/9d03b468-4b2e-11e5-8a8b-96d451f3ba41.PNG)

**Comment by gerrykelly** [comment]
It needed the hyphen to break the word for the printed report.  What happens in the browser varies,  I resized columns so Classification now fits on one line in all cases

**Comment by rssidlowski** [comment]
Missing an "I" in classification.

**Comment by gerrykelly** [comment]
Who can see an "I" in 8pt Arial Narrow!  Fixed

**Comment by rssidlowski** [comment]
Verified with Gerry's link.  Please update in the Activity manager.

**Comment by jday3** [comment]
done

**Comment by rssidlowski** [comment]
Verified in COB dev.
Please promote to COB Prod.

**Comment by gerrykelly** [comment]
ready for the prod activity manager

**Comment by jday3** [comment]
now in production

**Comment by rssidlowski** [comment]
Verified in production.
