### ISSUE TITLE
Report: new PST Classification Report

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#187]
New PST Classification report requested.
![pstclass](https://cloud.githubusercontent.com/assets/5039052/9408100/83ce8c74-47dd-11e5-930f-be0b17a74c19.PNG)
Please pass to Jesse when complete so he may add to the Activity Manager.

**Comment by gerrykelly** [comment]
This new report -- "PST Classification Report" (reportType=SDUOclass in the request URL) needs to get into the Activity Manager (both dev and prod). The URL/query string is like for the two SDUO reports back in May ... sample below (so presenting a date range and multi-select for the Discharge Classifications)

http://dpwview.baltimorecity.gov/SDUO/SDUO.aspx?reportType=SDUOclass&d1=02/8/2015&d2=08/22/2015&vals=1,3

**Comment by jday3** [comment]
This is now in available in the activity manager (dev and prod)

**Comment by rssidlowski** [comment]
Verified.
