### ISSUE TITLE
Add item to field and lab results

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#188]
From Stakeholder at COB: I would like to request an addition to the PST application.  We would find it very useful if the selection from the drop down box in the Dye test field of the investigation sample page was included on the right side of the sample list along with the field and lab results.
![pstenh](https://cloud.githubusercontent.com/assets/5039052/10946885/b39e7d38-82f2-11e5-8021-4cfde9b67d78.png)

**Comment by gerrykelly** [comment]
done in dev.  See investigation 292 samples list as example.  If this is what they are looking for I'll deploy in prod after hours.

**Comment by rssidlowski** [comment]
Verified.

**Comment by gerrykelly** [comment]
done in prod

**Comment by rssidlowski** [comment]
Verified in prod and approved by COB.
