### ISSUE TITLE
Investigation sample: typo on message for missing calculation method

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#19]
To recreate, click on calculate without selecting a calculation method.  Get the error message shown below:
![missingcalcmethod](https://cloud.githubusercontent.com/assets/5039052/4763897/7bda91ea-5b19-11e4-805b-d9c05d503604.GIF)
'Methord' should be 'method' in the text of the message.

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
