### ISSUE TITLE
Time on sample reducing by one hour on each save

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#190]
As reported from the users:   The sample times that we are inputting into the sample pages are being reduced by one hour each time a page is saved. For every new entry the time is decreasing and each time a change is made elsewhere on the page to a recently entered sample the time is also decreased.  This has been occurring since the beginning of this week and seems to be only effected by new entries.  If changes are made and saved to entries inputted prior to this week the times are not changed.  The problem is occurring on both desktop and mobile versions. 

Verification:  I added a new investigation at 1:24pm today titled Regina's test and the sample time is 12:24. 

![time](https://cloud.githubusercontent.com/assets/5039052/11005130/253559ec-848a-11e5-884f-779f84648c46.PNG)

**Comment by gerrykelly** [comment]
Should be fixed in dev and prod.  If so, we should recheck when daylight savings time starts again.
If the code (and lack thereof) that caused this is in other apps (SSO) I believe that a similar problem would occur for some combination of edits in EST vs EDT and dates in one or the other.

**Comment by rssidlowski** [comment]
Verified. Asking COB to verify as well.

**Comment by rssidlowski** [comment]
Verified by COB.
