### ISSUE TITLE
Dye Duration: allow free form

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#191]
On the sample page, change the "Dye Duration (min)" to "Dye Duration" and allow entry of free form and not just minutes.  They want to be able to enter "2 hours 15 minutes".

**Comment by gerrykelly** [comment]
if we are not "fixing" it for the reasons discussed, then I think we should leave it as "Dye Duration (min)" since it remains a numerical field and that is the measure. ... but if you still want it changed, just assign it back to me.
Again, if they want "2 hours 15 minutes", key in "135"
