### ISSUE TITLE
Map Sample List: display in reverse chronological order

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#192]
When displaying a list of samples from selecting on the map, display the results in reverse chronological order with the newest on the top.
![mapsample](https://cloud.githubusercontent.com/assets/5039052/11271665/8482d216-8e95-11e5-8dfc-72f5291cea03.PNG)

**Comment by gerrykelly** [comment]
Done and working in dev.  This was not straightforward since that list is used for more than just samples and the date was not really a data attribute.  So please test showing the list for samples the adding a sample with the snap placement, selecting multiple samples in the map, etc.

**Comment by rssidlowski** [comment]
Verified in Dev.  Ready for prod.

**Comment by gerrykelly** [comment]
done in prod
