### ISSUE TITLE
Report: PST Details add investigation comments

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#193]
From COB:
We are working on our NPDES Report; can you add the Investigation Comments field (field is called Explanation) to the PST Details Report?  Perhaps add as the next line for each or on the right if there is room.
![pstdetailreport](https://cloud.githubusercontent.com/assets/5039052/11273045/1666b8ba-8e9f-11e5-91d7-bc98afcb9db7.PNG)

Please update the  category classification “filter data” for the PST Details Report to include “None” and “Other”.  These are 2 discharge classifications that were added to the APP.  There may be more requests as we try to summarize data for our report.

**Comment by gerrykelly** [comment]
Doing this for prod only.
1) There no field "comments" there is the field INC_DESC that comes from the "Explanation" input from the Investigation form.  I added that to the report (example with the "new" values of "none" and "other" also: http://dpwview.baltimorecity.gov/SDUO/rptPST.aspx?reportType=detail&date1=1/1/2010&date2=12/31/2010&SDUOS=1,0,2,3,4,5
2) For the “filter data” part, if those values are not showing I think that is something to ask Jesse to do

**Comment by rssidlowski** [comment]
Jesse, can you update the filter for the pst_detail report to include  "none" and "other"?

**Comment by jday3** [comment]
completed
