### ISSUE TITLE
Reports: migrate updated reports to production on web site.

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#194]
Migrate the reports described in #189 to production: 
These three reports needed to be moved to the http://dpwview.baltimorecity.gov/sduo/*** URL. So, we need to ask Jesse to repoint them from the UI like he has done for some other reports that were moved.

**Comment by rssidlowski** [comment]
Reports are: 
Complaints
Investigations by Status by date range
Investigations by Complainant for date range

**Comment by jday3** [comment]
complete
