### ISSUE TITLE
Search by QC Status and date range: include null in search

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#198]
The search allows user to search using the data in the list:
- Needs QC
- QC Complete
- N/A
- Partial (Investigation Active)

Add NULL to the list so can search for items with No QC status in the requested date range.
![qclist](https://cloud.githubusercontent.com/assets/5039052/14851275/d5630bf8-0c4c-11e6-943c-52abd527ac18.PNG)

**Comment by gerrykelly** [comment]
Done by adding "NULL Value" to the source table and adding new query to the web services to handle null values (and replacing the dll on the dev server)

**Comment by rssidlowski** [comment]
Unable to select the QC Status on the iPad.  Can we review when you are in the office?

**Comment by gerrykelly** [comment]
should be working now

**Comment by rssidlowski** [comment]
This works fine. Please promote to prod.

**Comment by gerrykelly** [comment]
in prod

**Comment by rssidlowski** [comment]
Verified.
