### ISSUE TITLE
Investigation Sample: save message has typo

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#2]
On save for a new sample the message below is displayed.
![samplesave](https://cloud.githubusercontent.com/assets/5039052/4705384/33f1439c-587b-11e4-81fd-4f9fd5f6193a.GIF)
Change 'sunccessfuly' to 'successfully'

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
