### ISSUE TITLE
Lab Data: update the list entry display

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#20]
on the lab data list see the following:
![labdatalist](https://cloud.githubusercontent.com/assets/5039052/4763927/0cdea4e2-5b1a-11e4-9284-1f9c664f8f69.GIF)

Update the list to include: Lab Name, Parameter, Operator and value for each entry.

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
