### ISSUE TITLE
Download full PST database as excel not working

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#200]
When attempting to download full PST database as excel workbook, get a warning message about the page trying to load form unauthenticated sources. When opt to load unsafe scripts, the download never completes.
![pstdownload](https://user-images.githubusercontent.com/5039052/27970329-740e0862-631c-11e7-842b-68a2be6c9319.jpg)

**Comment by alanfoster99** [comment]
Here is what I am seeing as the error:

VM115:1 GET https://dpwview.baltimorecity.gov/water/PSTwebAPI/api/PST/MakeExcelFile?_dc=1499451144090 500 (Internal Server Error)

**Comment by taojun545** [comment]
I have fixed the issue on both DEV and Production, and please check!

The application was trying to load 'EPPlus, Version=4.0.5.0', but there is only 'Version 3.0.0.2' on file. So I updated the correct version, and it fixed the issue.

**Comment by rssidlowski** [comment]
Verified in dev and prod.

**Comment by rssidlowski** [comment]
Awaiting verification from the cob client.

**Comment by rssidlowski** [comment]
Verified with the client (Joan), that this is working fine. Closing.
