### ISSUE TITLE
Lab Data: update the detail entry screen to remove lab id, add 'add another' button

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#21]
Current lab data detail screen is:
![labdetails](https://cloud.githubusercontent.com/assets/5039052/4763942/77598454-5b1a-11e4-85f8-bea56706d675.GIF)
Update to 
1. remove lab test id.
2. add a button to allow to add another lab test after the current selection has been saved.  
When add another lab test  is clicked clear the current screen if the current data has been saved.
If the current data has not been saved, prompt user to ask if they want to save the current data first.

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
