### ISSUE TITLE
Search: provide the ability to search for all investigations

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#24]
From the search screen, allow the user to select all.  This may be too large, but they have asked for this capability.  Can we see if this is too big to manage?

**Comment by kanglu666** [comment]
there will be over 1000 records of investigation...not sure if they really want show them all.
maybe just show recently investigation?

**Comment by rssidlowski** [comment]
Closing this for now.  I think the searches we have are fine.
