### ISSUE TITLE
Map Identify: allow users to click on Identify on map

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#25]
From the map, allow the user to click on the Identify then select a location on the map and display the resulting investigation/sample features in the list below within the range.

Alternatively, if the user selects an actual item on the map, display only that sample feature below.

**Comment by kanglu666** [comment]
identify function done:  identify sample -> list associated investigation

**Comment by rssidlowski** [comment]
Verified.
