### ISSUE TITLE
Link sample: change message text

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#26]
To recreate:
1. select an investigation (or search for one)
2. go to sample list
3. click on link sample button
get message
![linksamplemsg](https://cloud.githubusercontent.com/assets/5039052/4764276/04ca0a96-5b22-11e4-951e-c099ad292fba.GIF)
change message text to read:
Find another sample to link to this Investigation?

When linking only allow user to link samples of location type sample, not initial or source.

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
