### ISSUE TITLE
Lab Data: change text on delete confirmation message

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#28]
When attempting to delete lab data record, the confirmation message is: 
![labdeletemsg](https://cloud.githubusercontent.com/assets/5039052/4790653/c8d771b8-5dd3-11e4-9556-3bf41dd71175.GIF)
Change to state: 
Are you sure you want to delete this lab data?

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
