### ISSUE TITLE
Sample: change text on save with missing data message

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#29]
When attempt to save a new Sample record but have not entered all required fields (including sample date), get presented the following message:
![sampledatemsg](https://cloud.githubusercontent.com/assets/5039052/4791019/7eebd3c8-5dd8-11e4-9a4c-aaf8ce8e4954.GIF)
Change text to:
Sample date field cannot be null.

**Comment by kanglu666** [comment]
updated

**Comment by kanglu666** [comment]
updated at city dev, please test.

**Comment by rssidlowski** [comment]
Verified.
