### ISSUE TITLE
Link Sample: no features found only link to samples

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#30]
When attempting to link a sample to an existing investigation get message, but have selected a spot where there is an investigation: 
![nofeaturefound](https://cloud.githubusercontent.com/assets/5039052/4791121/a613af60-5dd9-11e4-8820-6e4a02394d59.GIF)

Should only be able to link features of type sample (not source or initial).  I was able to link a sample of type source to an investigation.  See below, sample 21 was linked.

![linkedsample](https://cloud.githubusercontent.com/assets/5039052/4791302/88548b8c-5ddb-11e4-9841-dcc36735f487.GIF)

**Comment by kanglu666** [comment]
fixed by update map service

**Comment by rssidlowski** [comment]
Verified.
