### ISSUE TITLE
Link Sample: message text on confirmation message

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#31]
When associating a sample to an investigation, get the following confirmation message: 
![sampleassociated](https://cloud.githubusercontent.com/assets/5039052/4791320/cd8989f0-5ddb-11e4-81f1-2bf46ea73f26.GIF)
Change text to the following:
Selected sample has been associated with investigation.

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
