### ISSUE TITLE
Delete Sample: confirm before delete if associated with more than one investigation

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#32]
After linking a sample to an investigation, should prompt if user attempts to delete the sample. 
Current message is displayed:
![sampledeletemsg](https://cloud.githubusercontent.com/assets/5039052/4791558/4509b732-5dde-11e4-9170-b91783b804c7.GIF)

When user clicks on the 'delete sample', prompt with message:
If sample is only associated with one investigation only present this message:
"Are you sure you want to delete this sample?"
If sample is associated with more than one investigation present the following:
"This sample is associated with the following investigations:
--List investigation name and complainant dates here
![investigationlist](https://cloud.githubusercontent.com/assets/5039052/4791589/8d25739e-5dde-11e4-8daf-0628edb4980d.GIF)
Are you sure you want to delete this sample?"

**Comment by kanglu666** [comment]
delete sample warning message has been updated

**Comment by rssidlowski** [comment]
Message is:
![deletesample](https://cloud.githubusercontent.com/assets/5039052/4843116/f6144cee-602d-11e4-8841-88ab7bd05089.GIF)
Update to:
Warning: This sample may be linked to other investigations.  Are you sure you want to delete this sample?

So, we cannot display the other investigation in this message?

**Comment by kanglu666** [comment]
updated, 
and if the sample is associated with other investigations, the message will show investigation id

**Comment by rssidlowski** [comment]
This is not working as described. See below that the sample is associated with two investigations:
![samplestoinv](https://cloud.githubusercontent.com/assets/5039052/4866071/2c255ac0-6129-11e4-94d6-7fdf68362d46.GIF)

When I attempt to unlink I see the following message:
![unlink](https://cloud.githubusercontent.com/assets/5039052/4866073/381dae86-6129-11e4-917b-7614aa6a4b7f.GIF)

And then it is confirmed.
![unlinkconf](https://cloud.githubusercontent.com/assets/5039052/4866074/402a7398-6129-11e4-94d0-9b1984b540d6.GIF)

**Comment by kanglu666** [comment]
you are doing wrong workflow.
"Unlink" sample to investigation no means "delete" this sample.
Delete sample function is in the sample detail page, there is a Delete Sample button for this.

**Comment by rssidlowski** [comment]
You are correct.  This is working fine.
