### ISSUE TITLE
Discrepancy: Add to the top toolbar the ability to add a discrepancy

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#34]
Similar to the 'Add GIS Discrepancy' in the Utility viewer, add this button to the PST application and should have the the same function as the discrepancy on the Utility Viewer.
![discrepancy](https://cloud.githubusercontent.com/assets/5039052/4792567/9e3e429c-5de7-11e4-931e-36f286b90222.GIF)

**Comment by kanglu666** [comment]
i will add this function once we move to city dev

**Comment by rssidlowski** [comment]
Can you add this to the city dev environment?

**Comment by kanglu666** [comment]
add discrepancy function has been added into city dev, please test

**Comment by rssidlowski** [comment]
Verified.
