### ISSUE TITLE
Label on browser tab: Pollution Source Tracking misspelled

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#36]
the label on the browser tab is 'Polution Source Tracking'.  See below:

![browserlabel](https://cloud.githubusercontent.com/assets/5039052/4793201/27e3e714-5dec-11e4-8264-2d2c77e40375.GIF)

Change the label to:
Pollution Source Tracking

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
