### ISSUE TITLE
Toolbar: hover over display text

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#37]
When the user hovers over the toolbar item display text for each item in the toolbar:
![toolbar](https://cloud.githubusercontent.com/assets/5039052/4793279/b0a0cebe-5dec-11e4-9acf-6ebe4c28457c.GIF)
DPW Portal Page
Full Extent
Zoom In
Zoom Out
My Location
Identify
Add New Investigation

**Comment by kanglu666** [comment]
this is a mobile app, cant do the tool tip function as desktop app.
