### ISSUE TITLE
Sample List: scrolling not working 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#38]
To recreate:  
1. search by investigation id, enter 924
2. click on Samples
3. get large list
4. scroll down
Unable to scroll to the bottom of the list...it keeps coming back to the top.

![samplelistscrolling](https://cloud.githubusercontent.com/assets/5039052/4793454/192e8b96-5dee-11e4-9b3c-5ff201531f86.GIF)

If I exit from the sample list (hitting the back button) and come back I am able to scroll down.
I recreated on the iPad.

**Comment by kanglu666** [comment]
fixed

**Comment by rssidlowski** [comment]
Verified.
