### ISSUE TITLE
Report: Investigations per Watershed by Year

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#39]
Description: this report is a summary of the number of Investigations reported (created) in a calendar year by watershed. Also include a total for each watershed for all years included in the report and a total for each year's number of Investigations.
Inputs: User can enter up to 10 years to include.
Sample output.

![image](https://cloud.githubusercontent.com/assets/5039052/4794305/ef6a549c-5df3-11e4-96e1-45bac285eb78.png)

**Comment by rssidlowski** [comment]
Update title to capitalize 'Selected'.
![investigations by year selected watersheds](https://cloud.githubusercontent.com/assets/5039052/4995622/05ba56be-6990-11e4-9d32-42e78e758e9e.GIF)

**Comment by rssidlowski** [comment]
Unable to select a year on the DPW Activity manager.
![reportincwatershedyear](https://cloud.githubusercontent.com/assets/5039052/5107469/121753a8-6fd0-11e4-8f3b-08590c28bc52.GIF)

**Comment by kanglu666** [comment]
fixed, please clear browser cache and test

**Comment by rssidlowski** [comment]
Verified.
