### ISSUE TITLE
Report: SDUO/ Discharge Classification Report

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#46]
Description: this report is a list of the investigations reported (created) in a specified date range which are SDUO. 
Inputs: User selects the from and to date to include.
Sample output.
Title at Top:  
SANITARY DISCHARGE UNKNOWN ORIGIN (SDUO)
From 01/01/2014 to 06/30/2014

Report is in Date order and includes the following Fields:
Create Date
Name
Location Description
Problem  Type
Watershed
Stream Name
Status

Include a total for the number of SDUO in the specified date range at the end of the report..

**Comment by gerrykelly** [comment]
ready for testing as noted and pending Lu's work on the UI

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
From COB personnel:
I had noticed that the SDUO report is not correct. Currently, when the SDUO report is generated; it includes all the PST investigations within the specified date range. It should only have SDUO information collected in the specified date range. Below is how the SDUO report should look.
![sduo1](https://cloud.githubusercontent.com/assets/5039052/6802945/aed77730-d20a-11e4-9463-8330a140db16.jpg)
![sduo2](https://cloud.githubusercontent.com/assets/5039052/6802948/b20b02c8-d20a-11e4-8126-d1c7149e3514.jpg)

**Comment by rssidlowski** [comment]
See below:
![dischclassreport](https://cloud.githubusercontent.com/assets/5039052/7165878/5edba2e0-e378-11e4-8c73-e5ea0cea4043.PNG)

**Comment by rssidlowski** [comment]
Revised to two reports. This report becomes the 'investigations with Discharge Classification' and allows user to enter a date range and select any number of Discharge Classification values as defined on the Investigation record.  
Here is a sample mockup of this report:
![dischclass](https://cloud.githubusercontent.com/assets/5039052/7394963/fe446a00-ee64-11e4-8968-0a30a8d8184d.PNG)
![dischclass2](https://cloud.githubusercontent.com/assets/5039052/7394966/01ba8142-ee65-11e4-9231-465b4f773388.PNG)

The second report is all investigations that have at least one sample with SDUO at the sample level.  Only list the samples that are classified as SDUO.  Allow user to enter date range.
![sduosamples](https://cloud.githubusercontent.com/assets/5039052/7394993/294988c0-ee65-11e4-818f-84707b133a54.PNG)

**Comment by gerrykelly** [comment]
Note that I had to do these in VS 2013 with all other reports in 2010, so they needed to be their own web app.  Not ideal, but not a problem.  The code is in the same place as the other reports in SVN.

**Comment by gerrykelly** [comment]
The 2 SDUO reports are done same in dev as prod (so for the below, the only difference is “dev” vs. “view” in the URL)

For the 1st report -- Investigations with Discharge Classifications – you need have the UI send a URL with  … SDUO/SDUO.aspx/  then the query string like below, 

http://dpwview.baltimorecity.gov/SDUO/SDUO.aspx?reporttype=1&vals=1,2,3,4&d1=1/1/2009&d2=1/1/2014

Where the vals parameter is the DC_ID from the table below.  So you would show the DC_DESC in the UI with the option to select multiple and make a CSV string for the query.  (Do we really want to show “None” as an option?, I don’t see why we would)

gis_admin_PST_DISCHARGE_CLASSIFICATION
DC_ID   DC_CODE DC_DESC
0                               None
1           SDUO            SDUO
2           SSO                     SSO
3         SSOP         SSO_Private
4          PW               Potable Water

Then d1, d2 are the date-range (works also with leading zeros for the day/month)

The 2nd report -- Investigations with SDUO Samples -- just needs the reporttype and the date range:
http://dpwview.baltimorecity.gov/SDUO/SDUO.aspx?reporttype=2&d1=1/1/2009&d2=1/1/2014

**Comment by rssidlowski** [comment]
The nitrate+nitrate is missing the left parenthesis: This is in both SDUO reports.
![sduoreport2](https://cloud.githubusercontent.com/assets/5039052/7522251/f6c7d27c-f4c1-11e4-88f5-db9c3f0c8faa.PNG)

![sduoreport](https://cloud.githubusercontent.com/assets/5039052/7522188/9b5d59fc-f4c1-11e4-8982-558967f45ff1.PNG)

**Comment by gerrykelly** [comment]
fixed

**Comment by rssidlowski** [comment]
Nitrate+Nitrate should be Nitrate+Nitrite.

**Comment by gerrykelly** [comment]
Done

**Comment by rssidlowski** [comment]
Verified in COB dev.  Needs to be moved to production.

**Comment by gerrykelly** [comment]
you should be seeing the same in prod, I made the same changes in both places.

**Comment by rssidlowski** [comment]
I got further clarification on the Discharge Classification report from COB personnel.
The TKN values are actually the "Kjeldahl Nitrogen (Total)" in the parameters for lab data and the Nitrate+Nitrite is associated to the "Nitrate+Nitrite-Nitrogen" in the parameters for lab data.

**Comment by gerrykelly** [comment]
Yeah, that makes sense ... you should have known that :-)
Changed in dev & prod, please do a spot check against original data if you can

**Comment by rssidlowski** [comment]
I verified some samples. Looks good to me.  Will have COB personnel verify.
