### ISSUE TITLE
Photo: assign category

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#49]
Update the 'Photo' page to allow the ability to associate a photo category to each photo as it  is uploaded and after (allowing user to update the photo category).

See #48 for categories.

**Comment by kanglu666** [comment]
need to discuss

**Comment by rssidlowski** [comment]
See attached.
![photo_categories](https://cloud.githubusercontent.com/assets/5039052/4842953/f39335c2-602b-11e4-8643-5ee6ea7f649d.png)

**Comment by kanglu666** [comment]
update/add photo category function has been added in city dev. please test

**Comment by rssidlowski** [comment]
I don't see this in the app.
![existingimages](https://cloud.githubusercontent.com/assets/5039052/4865958/3d6e3a1e-6128-11e4-9788-5fe9668d034e.GIF)

**Comment by kanglu666** [comment]
this is done in the investigation photo. 
Just saw the PST_SamplePhotos table in DB, i'll work on the sample photo.

**Comment by rssidlowski** [comment]
Category needs to be added to the Sample photo upload.

**Comment by kanglu666** [comment]
looks like the PST_SamplePhotos table has no Category filed.
i mean, from out DB, there is no relationshil between photo category and sample photo.

**Comment by rssidlowski** [comment]
Update photo category since cannot see all the text.  Currently displays:
![photocategory](https://cloud.githubusercontent.com/assets/5039052/4952390/7c116d36-6673-11e4-9eca-1a9ef5eee536.GIF)

Either extend the length of the display field or shorten the first two names to
"Initial Pollution Obs Before Fix"
"Initial Pollution Obs After Fix"

Add the ability to clear the category or add the value "None"

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
