### ISSUE TITLE
Data: Personnel active list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#50]
Please activate the following personnel as city inspectors in the PST_Personnel table:
M. Cherigo
T. Eucare
V. Sturtevant
N. Mistrus
M. Schlenoff
J. White

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
I don't know where this was done and how I can verify. I looked at personnel in the city dev and see all listed in the personnel list.

**Comment by kanglu666** [comment]
updated at city dev. please test

**Comment by rssidlowski** [comment]
Verified.
