### ISSUE TITLE
Investigation: Service Requests

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#51]
Add a field to the user interface to allow the user to associate multiple Service Requests to this investigation (from the table PST_SERVICE_REQUESTS). This should be displayed on the Investigation page.
The system needs to be able to add new entries to the PST_SERVICE_REQUESTS.

**Comment by kanglu666** [comment]
new function added at city dev

**Comment by rssidlowski** [comment]
Verified.
