### ISSUE TITLE
Investigation Sample: Change 'Odor Rusty/Sweet' to 'Odor Fruity/Sweet'

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#52]
Change 'Odor Rusty/Sweet' to 'Odor Fruity/Sweet' in the PST_SAMPLES table.

Please pass ticket along to Lu to change in the user interface. Change on the Investigation Sample page.

**Comment by kanglu666** [comment]
updated at city dev

**Comment by rssidlowski** [comment]
Verified.
