### ISSUE TITLE
Map: change symbology 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#53]
Change symbology on map to:
Star for Source
Circle for Initial Pollution Observation
Square for Sample

Here is what the current system has:

![symbology](https://cloud.githubusercontent.com/assets/5039052/4826081/354d1dfe-5f6c-11e4-9b83-2ec04cd76d4e.GIF)

**Comment by JMurk** [comment]
Updated.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
Please change the color/shape for the sample from a yellow square since that is what we have for buildings.  Can you make it a diamond symbol instead?

**Comment by JMurk** [comment]
Updated.  Let me know if that works.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
Can you change the color - the yellow blends in with the background/buildings.  How about pink or red?

**Comment by JMurk** [comment]
Check it out now.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
Comments from COB personnel: Can you make the new diamonds larger and red so that they stand out, the change that was made is still too subtle.  Can the sample, source, etc. markers be a larger size and a brighter color (non-pastel)?
We currently have: 
![symbols](https://cloud.githubusercontent.com/assets/5039052/5760843/5a093e18-9ca5-11e4-9a6a-604c86b9df78.GIF)

Please make all larger and change Samples to be bright red. Can you make the Green for the Sources star darker?

**Comment by JMurk** [comment]
Updated to:

![image](https://cloud.githubusercontent.com/assets/5805454/5779299/ae0e3296-9d6f-11e4-9f95-8c0ee3a7dd5f.png)

**Comment by rssidlowski** [comment]
Verified.
