### ISSUE TITLE
SR Number: typo on confirmation message

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#54]
If click on the Add button without entering an SR number, message presented is:

![srmsg](https://cloud.githubusercontent.com/assets/5039052/4831722/ce7e941a-5f96-11e4-8bd9-a580f1e76cbf.GIF)

Change to 'Please enter service request number to add!'

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
