### ISSUE TITLE
Settings: domain values to allow users to update 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#56]
The following domain values need to be available for authorized users to update in the Settings on the mobile application:
PST_ComplainantSourceCodes
PST_Personnel
PST_RefAgencyCodes
PST_QCStatuscodes

**Comment by kanglu666** [comment]
new function has been added. please test at city dev.

Settings --> Editting Domains(at the bottom)

**Comment by rssidlowski** [comment]
Change the spelling of 'Editting' to 'Editing'.
![editting](https://cloud.githubusercontent.com/assets/5039052/4864423/2e53bd44-611c-11e4-8940-32e6a966b7a7.GIF)

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Still displays as "Editting" with two "t's".

**Comment by kanglu666** [comment]
??

**Comment by rssidlowski** [comment]
Verified.
