### ISSUE TITLE
Sample: provide the ability to move the location of a sample

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#57]
Once a sample is saved allow the user the option to move the location of the sample.  Allow the user to select a method (just as they do on the initial creation of the sample) of either snap or spot.  
Let me know if you need more details.

**Comment by rssidlowski** [comment]
Making this lower priority for now.  They can delete and add a new sample if needed.

**Comment by rssidlowski** [comment]
SME for COB are interested in this functionality.  How difficult it this?  What is the level of effort?

**Comment by gjmkelly** [comment]
This is testable for the "spot" method and pending the answers I get regarding the "snap" method, I'll finish it.  So, it's a little quirky but check it out to see if it's basically what we want.
From the samples detail page you click on the new "Move" button (I think it makes sense only doing it this way rather than trying to directly start at the map).  Then follow through and choose spot.

**Comment by rssidlowski** [comment]
I verified the existing functionality for the spot vs. snap. The spot associates the point to the exact spot you select and if there is an existing feature there it will enter the type in the system type.  If you select a spot with no feature it puts Unknown in the system type.  

So for the move of a sample, we want the spot to enter the exact spot the person clicks and if there is a feature at the spot enter that in the system type, if none there, enter unknown.

When selecting snap, it does save the location at the exact spot of the selected feature.

**Comment by gjmkelly** [comment]
I think this is working well. Part of what we were seeing is that when a new sample was set to snap it would do so when selected in the list, but NOT when the user went right to the disclosure arrow on the list.  I also removed storm drains from the list as discussed.

**Comment by rssidlowski** [comment]
Verified.

**Comment by rssidlowski** [comment]
This is not working.   Tried to move via the spot method, saved and it reverts back to the original spot.
Also tried to move via the snap and cannot see all items in the resulting circle.
Also when do a move, get the loading just clocking. COB personnel reported these items and I am having trouble moving a sample and seeing the same as described.  Let me know if you want to go over it together.

**Comment by gerrykelly** [comment]
working, but I need to have the code update the system type field in some cases

**Comment by gerrykelly** [comment]
This was only working for one workflow out of a few.  Should now work for all cases.

**Comment by rssidlowski** [comment]
Verified.
