### ISSUE TITLE
Settings: display domain values in alphabetic order

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#59]
After adding new domain values (e.g. to the complainant list), display in alphabetic order instead of at the end of the list.

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
After adding a new Complainant it is displayed at the bottom of the list in the setting domains page:

![settingdomains](https://cloud.githubusercontent.com/assets/5039052/4952723/3e588fce-6678-11e4-86e2-79b55a04416b.GIF)

**Comment by rssidlowski** [comment]
And it displays at the end of the list in the selection in the PST application: 
![complainantlist](https://cloud.githubusercontent.com/assets/5039052/4952754/7a8605a8-6678-11e4-8459-96bf9a9cc6d3.GIF)

**Comment by rssidlowski** [comment]
Verified.
