### ISSUE TITLE
Sample location type lookup

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#6]
For the following samples, the type lookup value should be Sample, not Source for the following sample_id's: 
4603, 4604, 4605, 4606.
![sampletypelu](https://cloud.githubusercontent.com/assets/5039052/4706361/15c406bc-5884-11e4-861e-96fbf18b0f1b.GIF)
But when viewing in the PST application, these are showing as type= Source, and not Sample.
![samplelist](https://cloud.githubusercontent.com/assets/5039052/4706370/28827cf2-5884-11e4-8582-cb96d39fb9b4.GIF)

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
