### ISSUE TITLE
Reports: Configure Activity Manager to allow for reports

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#61]
See design in M:\2010\13101078\Reports\Geospatial\Environmental Compliance\Design\Reports\Wireframes\v1.0.

Please provide link for testing when configured.

**Comment by kanglu666** [comment]
http://dpwdev.baltimorecity.gov/water/pstwebapinew/index.aspx

**Comment by rssidlowski** [comment]
Change the names of the reports in the Activity manager to have the word 'Investigation' instead of 'Incidents'.
Put the list in alphabetic order and should be as follows:
Complaints
Complaints Started by Month
Investigations by Status per Date Range
Investigations by Complainant per Date Range
Investigations Per Origin by Year
Investigations Per Status by Month
Investigations Per Status by Year
Investigations Per Watershed by Month
Investigations Per Watershed by Year
Investigations Per Problem Type by Year
PST By Problem Type and Status
PST Sheets
Sanitary Discharge Unknown Origin

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
