### ISSUE TITLE
Data: Flow method missing in samples table

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#62]
I see the flow method in the application, but the values are not filled in for samples where there are bottle size and time to fill values.  There should be a flow method field which selects from the two methods: volume or measurement.
For all the values with the bottle size, update the flow method to be 'volume'.

**Comment by gerrykelly** [comment]
1)  Actually it looks like all existing samples with flow data are the bottle method (please look and see if I am interpreting it right)
2) The data in PST_SAMPLES does not have vol_calc_method_id values for existing samples (I can calc these for the final migration now that we know the logic)
3) this comes from a data design issue (starting with FLOWNUM being mapped to FL_BOTTLE_SIZE) ... see Database_Design_Mapping_RSS_20140919.xlsx.  Please take another look at it;  I think we need to use FVOLUME for [FL_BOTTLE_SIZE] and set [VOL_CALC_METHOD_ID] to 2 for all the records where FLOWNUM = 1.  Then we can calc the CFS/GPM if desired (but those values can not map directly from anything in the existing samples table)

**Comment by rssidlowski** [comment]
1. Correct all existing samples use the volume aka bottle method.
2. Yes, all existing samples from legacy data should be coded with the vol_calc_method_id for volume.
3. Correct that we should be mapping from FVOLUME TO FL_BOTTLE_SIZE.  
   Note that they have requested to add a new flow method Manual and would like to set either the flow volume (CFS) or the flow volume (GPM).  See #70.
