### ISSUE TITLE
Add new discrepancy: need cancel button

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#63]
After selecting the 'add new discrepancy' button present a button to cancel the operation.
Currently displays: 
![newdiscrepancy](https://cloud.githubusercontent.com/assets/5039052/5011026/7eee283c-6a47-11e4-982d-36ccd3be05d4.GIF)

**Comment by kanglu666** [comment]
created a navigation back button, which will go back to the map and cancel the add discrepancy operation.

**Comment by rssidlowski** [comment]
Verified.
