### ISSUE TITLE
Search: add new search by sample name

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#64]
Similar to search by investigation name add the ability to search by sample name and allow the user to enter all or part of a sample name and display the results in date order by most recent date.

**Comment by kanglu666** [comment]
new search function added, please test

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
The search by sample is not working correctly.  For example I searched for 'Eastern' and got the following results:
![searchbysampnameeastern](https://cloud.githubusercontent.com/assets/5039052/5182911/5dcbfcf4-7476-11e4-8c07-25f75270bd04.GIF)
But, when I search for 'Run' I get no results.
![searchbysamplenamerun](https://cloud.githubusercontent.com/assets/5039052/5182923/7b4d3266-7476-11e4-93ff-301aae7e398e.GIF)

**Comment by kanglu666** [comment]
that's right.
you are searching for Sample Name, the results are Investigations which have the sample you searched.

**Comment by rssidlowski** [comment]
Aha.  thanks.
