### ISSUE TITLE
Data: add reference type

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#68]
We currently have service request and can have many associated to one investigation.  Additionally would like to have a reference category to include 
Work Order ID (Cityworks)
Service Request ID (311)

So add to the database table PST_SERVICE_REQUESTS a field REQUEST_TYPE_ID and have it look up to the domain table 'PST_RequestType'.

Once done pass this issue to Lu to update the application on the Service Requests page to do the following
1) change label at top to 'Investigation: References'
2) change to allow  user to enter 'Reference Number' and select from drop down 'Reference Type'.

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Add the reference type to be displayed with the reference number after it is added.
Add a reference type of "Other".

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
