### ISSUE TITLE
Settings: Change label from Source/Sample to Pollution Source Tracking

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#69]
On the settings page,change label from Source/Sample to 'Pollution Source Tracking'.
![settings](https://cloud.githubusercontent.com/assets/5039052/5015393/376ec5a6-6a6b-11e4-9ff8-604f9dc93d8d.GIF)

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
