### ISSUE TITLE
Search Investigation: after returning search results enable Map

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#7]
After initiating a search for an investigation by name and displaying the search results, the Map icon should be enabled allowing the user to select an investigation and display the investigation on the map. the Map icon is disabled.  Want to be able to allow the user to select what to display on the map and allow selection from a list: 
Initial Pollution Observation
Latest Sample
Source
![searchresults](https://cloud.githubusercontent.com/assets/5039052/4706963/7aa6d9c4-5889-11e4-9e24-7c6609520a52.GIF)

**Comment by kanglu666** [comment]
"Map" function from investigation has been finished, ready for testing.

**Comment by rssidlowski** [comment]
Verified.
