### ISSUE TITLE
Samples: new flow method

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#70]
On the samples form add a new flow method of 'Manual' and when the user enters manual they may enter either the CFS or GPM value.

![flowmethod](https://cloud.githubusercontent.com/assets/5039052/5015447/ac6bf7d4-6a6b-11e4-9232-3ff8b5e19a84.GIF)

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
