### ISSUE TITLE
Personnel: allow ability to enter free form personnel list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#71]
In addition to selecting the from the current list of personnel, allow the user to enter additional personnel in a free form manner.
Gerry:
Add field to PST_Samples called "ADDITIONAL_PERSONNEL"

When done pass to Lu:
Add the two fields to the Personnel page and allow user to enter either 
1) select from personnel list
2) free form enter Additional Personnel (need field in PST_SAMPLES)
3) free form enter Contractor Personnel (already have field in PST_SAMPLES)

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Added to the sample page and this is fine.
