### ISSUE TITLE
Samples: update number of decimals displayed

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#72]
Update the Samples page to have only 4 decimal places displayed.

Currently displays:
![decimals](https://cloud.githubusercontent.com/assets/5039052/5015586/12e7a2aa-6a6d-11e4-8c02-a8b751015ac4.GIF)

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
