### ISSUE TITLE
Map: include in results list inv name, sample name and date

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#73]
In the current map results list get the number and type
![mapresults](https://cloud.githubusercontent.com/assets/5039052/5015655/84c5dc48-6a6d-11e4-85c9-4732c54353cf.GIF)

change to have the results include: 
Investigation name, Sample name, Sample type and date

**Comment by kanglu666** [comment]
done.
Can't display Investigation name, because one sample may be associated with multiple investigation

**Comment by rssidlowski** [comment]
Verified.
