### ISSUE TITLE
Search: add new search by status and date range

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#74]
Add a new search function to allow user to enter status (selecting one status) and date range and return the results in reverse date order (most recent on top).

![search](https://cloud.githubusercontent.com/assets/5039052/5015758/703dc23a-6a6e-11e4-8f36-be16df4671f3.GIF)

**Comment by kanglu666** [comment]
new search function added, please test

**Comment by rssidlowski** [comment]
Verified.
