### ISSUE TITLE
Report: investigations by status for date range

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#75]
Allow user to select date range and one or all status values and present the results in reverse date order.
Report would be as follows:
## PST for Status: On-going Investigation for Date Range: 10/1/2014 - 11/12/2014

Name:    4616 Newgate     [inv_name]
Location:   Southwest corner of 4616 Newgate Ave. next to hydrant   [loc_desc]
Complaint Date:  2/10/2011  [inv_compldate]
Problem Type: Sewage   [problem_desc from PST_ProblemCodes]

Name:    4616 New     [inv_name]
Location:   Corner of 4616 Newgate Ave. next to hydrant   [loc_desc]
Complaint Date:  2/01/2011  [inv_compldate]
Problem Type: Sewage   [problem_desc from PST_ProblemCodes]

**Comment by kanglu666** [comment]
done
http://dpwdev.baltimorecity.gov/PSTReport/rptComplaint.aspx?Status=3,2&reportType=status&date1=11/18/2013&date2=11/18/2014

**Comment by rssidlowski** [comment]
Correct the spelling of investigations in the summary for each status type.  
Currently have 'investiagations'.
![reportstatus](https://cloud.githubusercontent.com/assets/5039052/5106110/b1a77ed8-6fc2-11e4-8e20-f24820c650c5.GIF)
Also, change 'Includes following status(s)' to 'Includes following status(es)'

**Comment by gerrykelly** [comment]
done and file -- rptInvStatDate.rdlc -- replaced in \VM-1108S08\AllReports

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
