### ISSUE TITLE
Report: investigations by complainant over date range

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#76]
Create a report of investigations over a date range by a specific complainant or set of complainants and group results by complainant and then sort by date for each complainant.

Sample report would be as follows:
## Investigations by Complainant for Date Range: 10/1/2014 - 11/12/2014

Complainant: WQMS
Name:    4616 Newgate     [inv_name]
Location:   Southwest corner of 4616 Newgate Ave. next to hydrant   [loc_desc]
Complaint Date:  11/10/2014  [inv_compldate]
Problem Type: Sewage   [problem_desc from PST_ProblemCodes]

**Comment by kanglu666** [comment]
done: http://dpwdev.baltimorecity.gov/PSTReport/rptComplaint.aspx?Status=3,2&reportType=status&date1=11/18/2013&date2=11/18/2014

**Comment by gjmkelly** [comment]
It looks like this is also calling the report for investigations by status over date range.  You want the example URL to be like:

http://dpwdev.baltimorecity.gov/PSTReport/rptComplaint.aspx?Complainant=42, 143&reportType=complainant&date1=1/1/2005&date2=12/31/2013http://dpwdev.baltimorecity.gov/PSTReport/rptComplaint.aspx?Complainant=42,%20143&reportType=complainant&date1=1/1/2005&date2=12/31/2013

… Gerry

**Comment by rssidlowski** [comment]
Correct typo: 'compainants' should be 'complainants' in the top line where it has: "includes following complainants"
![reportcomplainants](https://cloud.githubusercontent.com/assets/5039052/5106295/74ec03fe-6fc4-11e4-97e4-2a55481de1e8.GIF)
Correct typo in summary: 'investiagations' should be 'investigations'.
![reportcomplainantsinv](https://cloud.githubusercontent.com/assets/5039052/5106324/dbf710f2-6fc4-11e4-8baf-865293ea0fd8.GIF)

**Comment by rssidlowski** [comment]
In the activity manager, the complainant in the table below is empty and in this case should be populated with 'Blue Water Baltimore'
![reportcomplainantactmanager](https://cloud.githubusercontent.com/assets/5039052/5106469/8311f20c-6fc6-11e4-9e58-d36004a4d06b.GIF)

**Comment by kanglu666** [comment]
fixed, please test

**Comment by gerrykelly** [comment]
I corrected the typo.  Report file updated in: "\VM-1108S08\AllReports\rptInvComplainantDate.rdlc"

**Comment by rssidlowski** [comment]
Please correct the misspelling of 'investigations'.
![reportcomplainantinv](https://cloud.githubusercontent.com/assets/5039052/5112576/aa54684c-6ff6-11e4-8eaf-3c06298db48e.GIF)

**Comment by gjmkelly** [comment]
Lu, please replace rdlc file at City with "K:\User_VM\Gerry___temp\rptInvComplainantDate.rdlc"

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
