### ISSUE TITLE
Search: when item is selected from search results list go to sample not investigation

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#77]
Feedback from the COB personnel:

The current workflow is as follows:
1) user identifies current samples on the map and is presented with a list
![picksample](https://cloud.githubusercontent.com/assets/5039052/5037137/58137a66-6b53-11e4-9e72-7aee8d3cd5de.GIF)
2) user selects a sample from the list and is presented with the investigation

Change to present the sample instead of the investigation and allow the user to navigate to the investigation from the sample as it does currently.

**Comment by rssidlowski** [comment]
If a sample is associated with only ONE investigation can we have this go right to the sample?

**Comment by kanglu666** [comment]
identify sample function has been updated

**Comment by rssidlowski** [comment]
Verified.  Goes to sample and user selects an investigation.
