### ISSUE TITLE
Map: results list display values

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#79]
After selecting items on the map adjust the fields displayed in the results list.  Currently the following is displayed:
![picksample](https://cloud.githubusercontent.com/assets/5039052/5037308/c18f9154-6b54-11e4-9cf5-1d939caf60b4.GIF)
This display includes the sample ID and the type of sample.
Instead include: Sample name, date, investigation name.

**Comment by kanglu666** [comment]
you cant show the investigation name in the list, because one sample may be associated with multiple investigation.

**Comment by rssidlowski** [comment]
Can you just show the other information then?

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
