### ISSUE TITLE
Search by Investigation ID: display ID in results list

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#8]
When searching for an investigation by investigation id number, include the investigation id number in the results list: 
![searchbyid](https://cloud.githubusercontent.com/assets/5039052/4707048/31a0c978-588a-11e4-9eb7-111e4e1781ca.GIF)

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
