### ISSUE TITLE
New sample: unable to snap to wastewater manhole

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#81]
When attempting to create a new sample, unable to snap to a wastewater manhole.   Get no feature found message.  
![nofeature](https://cloud.githubusercontent.com/assets/5039052/5045807/86380d80-6bd0-11e4-9879-c1a4066e6797.GIF)

**Comment by kanglu666** [comment]
the sample feature is coming from Stormwater layers :  Stormwater Drains and Inlet only now.
what else layers you want to add?

**Comment by rssidlowski** [comment]
Stormwater End Structure
Stormwater Manhole
Stormwater Outfall
Wastewater Manhole
WQMS Outfall

**Comment by rssidlowski** [comment]
See #84.

**Comment by kanglu666** [comment]
updated

**Comment by rssidlowski** [comment]
Verified.
