### ISSUE TITLE
Create new PST map service to include all layers to select for new samples

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#84]
Please create a new map service called PST Map Service and include the map layers below which will be allowed to be selected for new samples.
Stormwater Drains
Stormwater Inlets
Stormwater End Structure
Stormwater Manhole
Stormwater Outfall
Wastewater Manhole
WQMS Outfall

**Comment by JMurk** [comment]
See my email response.

**Comment by rssidlowski** [comment]
Lu informed me that he could not allow the user to select from different map layers in different map services and suggested that Joe put them all in one service.  Can you verify that this is the case for the Sencha framework?

The WQMS Outfall is used in the current PST application.  Who can help me to identify what it is within the city environment?

**Comment by JMurk** [comment]
This map service is now published as PST_Selection_Features.  I kept all the symbology from the other map services (storm, sewer) and I still have no idea where to find a feature class for WQMS outfalls.

**Comment by rssidlowski** [comment]
Can you pull the outfalls shape file from the vm at the city 169.156.41.127 in the c:\outfalls\FieldData directory?

**Comment by JMurk** [comment]
WQMS outfalls should now be in that map service.  I also updated all the layer names to match the list above.
