### ISSUE TITLE
Investigation detail: make complainant category a drop down

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#86]
Associated with #67.
Make the complainant category field a drop down.

**Comment by rssidlowski** [comment]
Currently displays as: 
![complainantcat](https://cloud.githubusercontent.com/assets/5039052/5382176/f8f416b6-8075-11e4-943c-7d62a2e7c101.GIF)

**Comment by jday3** [comment]
Done, on dev

**Comment by rssidlowski** [comment]
Verified.
