### ISSUE TITLE
Investigation detail: make Status field wider

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#87]
on the Investigation detail screen adjust the size of the Status field  as part of the drop down so can see the whole field.
The drop down selection truncates.
![statusfield](https://cloud.githubusercontent.com/assets/5039052/5379944/816a637e-8062-11e4-992f-b65d69fa795b.GIF)
Alternatively shorten the descriptions to 
On-going Investigation
Ref to Agency, Repairs Pending
Ref to Agency, Not Resolved
Resolved
Stopped

**Comment by jday3** [comment]
Done, on dev. I just shortened the descriptions

**Comment by rssidlowski** [comment]
Verified.
