### ISSUE TITLE
Investigation Detail: adjust origin drop down values

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#88]
Update the dropdown list for Origin:
Add CityWorks
Remove Jones Falls, Herring Run and Harbor Watershed Associations and replace with Other
Remove WQMIS and WQMS replace with OCAL

**Comment by jday3** [comment]
Done, on dev

**Comment by rssidlowski** [comment]
Cityworks is one word.

**Comment by jday3** [comment]
Changed

**Comment by rssidlowski** [comment]
Verified.
