### ISSUE TITLE
Investigation Detail: adjust referral agency drop down values

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#89]
On the Investigation Detail, make the following adjustments to the referral agency data drop down and legacy data conversion needs to be adjusted.  Adjust the data first then I can update the values in the drop down from the application.
o   Replace Ralph Cullison/Mike Kohler  with Environmental Services
o   Remove  Water Analyer (misspelled in the list) - convert to Water Analyzer
o   Remove Eldon Gemmil’s name but keep Baltimore County-was Baltimore County (Eldon Gemmil)
o   Add – Asset Management
o   Add -  OCAL
o   Remove Waste Water Engineers - convert to Wastewater Engineering
o   Change - Wastewater Engineers to Wastewater Engineering
o   Change Sediment Control to Erosion & Sediment Control

**Comment by jday3** [comment]
Done, on dev

**Comment by rssidlowski** [comment]
Verified.
