### ISSUE TITLE
Search by Investigation ID: enable Map

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#9]
After displaying the results list from the search by investigation id, enable the map button and allow the user to select the location to display on map:
initial
latest sample
source
![searchbyid](https://cloud.githubusercontent.com/assets/5039052/4707094/a8489c2c-588a-11e4-9594-e92485e2482f.GIF)

**Comment by kanglu666** [comment]
done

**Comment by rssidlowski** [comment]
Verified.
