### ISSUE TITLE
Sample: adjust dye test values

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#91]
Investigation Sample changes 
Dye test – remove unknown, add inconclusive
Dye Color – remove unknown

**Comment by jday3** [comment]
Done, on dev

**Comment by rssidlowski** [comment]
Dye color - remove inconclusive
Dye test - add inconclusive

**Comment by jday3** [comment]
Fixed

**Comment by rssidlowski** [comment]
Verified.
