### ISSUE TITLE
Lab details: parameter list incomplete

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#93]
Please update with this complete list:
1,1,1-Trichloroethane
1,1,2,2-Tetrachloroethane  
1,1,2-Trichloroethane  
1,1-Dichloroethane  
1,2-Dichloroethane  
1,2-Dichloropropane  
2-Chloroethylvinyl Ether  
Acrolein  
Acrylonitrile  
Ammonia  
Ammonia Nitrogen  
Ammonia-Nitrogen  
Antimony  
Arsenic  
Benzene  
Benzene - 8021  
Biological Oxygen Demand  
BOD5  
Bromodichloromethane  
Bromoform  
Bromomethane  
Cadmium  
Carbon Tetrachloride  
Carbon Tetrachlorie  
Chemical Oxygen Demand  
Chloride  
Chlorine  
Chlorobenzene  
Chlorodibromomethane  
Chloroethane  
Chloroform  
Chloromethane
Chlorophyll-a  
Chromium  
Cis-1,3-Dichloropropene  
COD  
Conductivity  
Copper  
Diesel Range Organics by GC/FID  
Dissolved Oxygen
E. coli
Enterococcus Group  
Ethylbenzene  
Ethylbenzene - 8021  
Fecal Coliform  
Fluoride  
Gasoline Range Organics by GC/FID  
Hach Ammonia-Nitrogen  
Kjeldahl Nitrogen (Total)  
Lead  
Maximum Depth  
Methylene Chloride  
Microtox 15  
Microtox 30  
Microtox 30 min.  
Microtox 30 min. (pH adjust.)  
MPN Fecal Coliforms  
MTBE - 8021  
Naphthalene - 8021  
Nitrate Nitrogen  
Nitrate+Nitrite-Nitrogen  
Nitrite Nitrogen  
Nitrite-Nitrite Nitrogen  
Oil and Grease  
Ortho-Phosphate  
pH  
Secchi Disk  
Suspended Solids  
Tetrachloroethene  
TKN  
Toluene  
Toluene - 8021  
Total Coliform  
Total Petroleum Hydrocarbons  
Total Phenolics  
Total Phosphorus  
Total Xylenes - 8021  
Trans-1,2-Dichloroethene  
Trichloroethene  
Trichlorofluoromethane  
Turbidity  
Vinyl chloride  
Water Temperature  
Zinc

**Comment by gjmkelly** [comment]
done (table also includes "Total Organic Carbons", which is not in new list)

**Comment by rssidlowski** [comment]
Can you sort the list alpabetically?

**Comment by jday3** [comment]
Done, on dev. The list is now sorted

**Comment by rssidlowski** [comment]
Verified.
