### ISSUE TITLE
Data migration: not seeing photos associated with samples

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#95]
Not seeing photos that should be associated with samples.  I see the photos associated with investigations.  See below for some photos that should be associated with samples.
![missingphotos](https://cloud.githubusercontent.com/assets/5039052/5454140/114d8352-84fc-11e4-86e8-4461ddf95683.GIF)
But when I go to the PST application and find a sample: Franklintown Road:
![frank1](https://cloud.githubusercontent.com/assets/5039052/5454176/72127e40-84fc-11e4-8e21-f929056fc213.GIF)
There are no photos.
![frank2](https://cloud.githubusercontent.com/assets/5039052/5454177/7785deb2-84fc-11e4-9dda-8311e4b219a5.GIF)

**Comment by rssidlowski** [comment]
some photos are available and others are not.  
Missing these sample labels:
Franklintown Road
Stony Run Across from 4808 Wilmslow
Maple Glen Apartments

Also, when display a valid photo from another sample, and go into the photo page for one that has the photo missing, see the photo name from the last displayed photo, but no photo is displayed
![photomissing](https://cloud.githubusercontent.com/assets/5039052/5457218/122f3d5e-8517-11e4-8e5c-48f54f376c17.GIF)
.

**Comment by gjmkelly** [comment]
should work right now if my assumption about SAMPLE_IMAGES is correct, but we need to clarify with Lu what tables are or are not used and what I should do for the final migration

**Comment by rssidlowski** [comment]
verified.
Lu, can you tell us what table are and are not used related to images?

**Comment by kanglu666** [comment]
Gerry is right, SAMPLE_IMAGES is used for sample photos.

**Comment by rssidlowski** [comment]
Gerry do we need anything else from Lu?

**Comment by rssidlowski** [comment]
Verified this is working.
