### ISSUE TITLE
Personnel: adding personnel adds blank line

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#96]
When open a sample and attempt to add personnel to the list, in this example, attempted to add Matt Cherigo, adds a blank line. When I attempt to add again, get message that he is already there:
![personneladd](https://cloud.githubusercontent.com/assets/5039052/5473625/dba823a0-85d8-11e4-8b14-108bb2a59a41.GIF)

**Comment by jday3** [comment]
Fixed

**Comment by rssidlowski** [comment]
Verified.
