### ISSUE TITLE
Link to portal is incorrect in DEV - 404 error

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Pollution_Source_Tracking#98]
There is a link that is supposed to go to the DPWPORTAL page, but it generates an error.
In dev: http://dpwdev.baltimorecity.gov/water/pstwebapi/index.aspx, from the map, click on the Home icon on the top toolbar
![home](https://cloud.githubusercontent.com/assets/5039052/5526026/1a9d9116-89bd-11e4-9825-7308b7271ea4.GIF)
Get the confirmation message
![homenav](https://cloud.githubusercontent.com/assets/5039052/5526013/f1499468-89bc-11e4-89e7-a019e7762377.GIF)
and 404 error 
![homeerror](https://cloud.githubusercontent.com/assets/5039052/5526017/f80c383c-89bc-11e4-8667-4770a3f9dcc0.GIF)
The link is going to http://dpwdev.baltimorecity.gov/water/dpwportal and it should be going to http://dpwdev.baltimorecity.gov/water/portal/index.aspx.

**Comment by rssidlowski** [comment]
Also the Dev portal has a link for the Desktop Application labeled OAM Activity Manager, please update to DPW Activity Manager (as it is in production).
![oamactman](https://cloud.githubusercontent.com/assets/5039052/5526435/5ac92904-89c1-11e4-8046-daed14365fe0.GIF)
![dpwactman](https://cloud.githubusercontent.com/assets/5039052/5526437/5e1b140a-89c1-11e4-8b90-76e23a844189.GIF)

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Verified.
